<a href="https://colab.research.google.com/github/surapitttha/Deep-Learning-/blob/main/deep_learning_2_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีทักษะการเอาชีวิตรอดบางประการ ได้แก่:

(i) เทคนิคสำหรับการจัดเก็บและจัดการข้อมูล
(ii) ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
(iii) ความรู้เกี่ยวกับการดำเนินการพีชคณิตเชิงเส้นพื้นฐานที่เราใช้กับองค์ประกอบข้อมูลมิติสูง
(iv) แคลคูลัสเพียงพอที่จะกำหนดทิศทางในการปรับพารามิเตอร์แต่ละตัวเพื่อลดฟังก์ชันการสูญเสีย
(v) ความสามารถในการคำนวณอนุพันธ์โดยอัตโนมัติเพื่อให้คุณลืมแคลคูลัสที่คุณเพิ่งเรียนรู้ไปได้มาก
(vi) ความเข้าใจพื้นฐานเกี่ยวกับความน่าจะเป็น ซึ่งเป็นภาษาหลักของเราสำหรับการใช้เหตุผลภายใต้ความไม่แน่นอน
(vii) ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการเมื่อคุณติดขัด

โดยสรุป บทนี้จะให้คำแนะนำเบื้องต้นอย่างรวดเร็วเกี่ยวกับพื้นฐานที่คุณจำเป็นต้องรู้เพื่อติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้

**สรุป**

ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีพื้นฐานในด้านต่อไปนี้:

* เทคนิคการจัดเก็บและจัดการข้อมูล
* ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
* พีชคณิตเชิงเส้นพื้นฐาน
* แคลคูลัสพื้นฐาน
* การคำนวณอนุพันธ์โดยอัตโนมัติ
* ความน่าจะเป็น
* ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการ

บทนี้จะให้คำแนะนำเบื้องต้นเกี่ยวกับพื้นฐานเหล่านี้ เพื่อให้คุณสามารถติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้ได้

#2.1 Data Manipulation


2.1.1 Getting Started

To start, we import the PyTorch library. Note that the package name is torch.


In [ ]:
import torch

**การแปลและเรียบเรียง**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ในกรณีหนึ่งมิติ นั่นคือ เมื่อมีเพียงแกนเดียว เราจะเรียก tensor ว่าเวกเตอร์ ด้วยแกนสองแกน Tensor จะเรียกว่าเมทริกซ์ ด้วยแกนมากกว่า 2 แกน เราจะลบชื่อเฉพาะออกและเรียกวัตถุนี้ว่าเทนเซอร์อันดับ k

PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า ตัวอย่างเช่น ด้วยการเรียกใช้ arange(n) เราสามารถสร้างเวกเตอร์ของค่าที่มีระยะห่างเท่ากัน โดยเริ่มต้นที่ 0 (รวม) และสิ้นสุดที่ n (ไม่รวม) โดยค่าเริ่มต้น ขนาดของช่วงคือ 1 เว้นแต่จะระบุไว้เป็นอย่างอื่น เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**สรุป**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ใน PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**คำศัพท์:**

* Tensor: เทนเซอร์
* Array: อาร์เรย์
* Dimension: มิติ
* Vector: เวกเตอร์
* Matrix: เมทริกซ์
* Order: อันดับ
* Main memory: หน่วยความจำหลัก
* CPU-based computation: การคำนวณบน CPU

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

ค่าแต่ละค่าในเทนเซอร์เรียกว่าองค์ประกอบของเทนเซอร์ เทนเซอร์ x มี 12 องค์ประกอบ

เราสามารถตรวจสอบจำนวนองค์ประกอบทั้งหมดในเทนเซอร์ผ่านเมธอด numel ของเทนเซอร์ดังกล่าว

In [ ]:
x.numel()

12

เราสามารถเข้าถึงรูปร่างของเทนเซอร์ (ความยาวตามแต่ละแกน) โดยการตรวจสอบแอตทริบิวต์ shape ของเทนเซอร์นั้น เนื่องจากเรากำลังจัดการกับเวกเตอร์ที่นี่ รูปร่างจึงมีเพียงองค์ประกอบเดียวและเหมือนกับขนาด

In [ ]:
x.shape

torch.Size([12])


การแปลภาษา

เราสามารถเปลี่ยนรูปร่างของเทนเซอร์ได้โดยไม่เปลี่ยนแปลงขนาดหรือค่าของเทนเซอร์นั้น โดยการเรียกใช้ reshape ตัวอย่างเช่น เราสามารถแปลงเวกเตอร์ x ที่มีรูปร่าง (12,) เป็นเมทริกซ์ X ที่มีรูปร่าง (3, 4) ได้ เทนเซอร์ใหม่นี้จะเก็บองค์ประกอบทั้งหมดไว้ แต่จัดเรียงใหม่เป็นเมทริกซ์ โปรดสังเกตว่าองค์ประกอบของเวกเตอร์ของเราจะถูกวางเรียงทีละแถว ดังนั้น x[3] == X[0, 3]

In [ ]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

โปรดสังเกตว่าการระบุทุกองค์ประกอบของรูปร่างเพื่อ reshape เป็นสิ่งที่ไม่จำเป็น เนื่องจากเรารู้ขนาดของเทนเซอร์ของเราอยู่แล้ว เราสามารถคำนวณองค์ประกอบหนึ่งของรูปร่างได้โดยกำหนดส่วนที่เหลือ ตัวอย่างเช่น กำหนดเทนเซอร์ที่มีขนาด n และรูปร่างเป้าหมาย (h, w) เรารู้ว่า w = n/h เพื่ออนุมานองค์ประกอบหนึ่งของรูปร่างโดยอัตโนมัติ เราสามารถใส่ -1 สำหรับองค์ประกอบของรูปร่างที่ควรอนุมานโดยอัตโนมัติ ในกรณีของเรา แทนที่จะเรียก x.reshape(3, 4) เราอาจเรียก x.reshape(-1, 4) หรือ x.reshape(3, -1) ได้เทียบเท่ากัน

ผู้ปฏิบัติงานมักต้องทำงานกับเทนเซอร์ที่เริ่มต้นเพื่อให้มีค่า 0 หรือ 1 ทั้งหมด เราสามารถสร้างเทนเซอร์ที่มีองค์ประกอบทั้งหมดตั้งเป็น 0 และรูปร่างของ (2, 3, 4) ได้ผ่านฟังก์ชัน zeros

In [ ]:
x.reshape(4,-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
x.reshape(2,-1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.zeros(2,3,4).shape

torch.Size([2, 3, 4])

ในทำนองเดียวกัน เราสามารถสร้างเทนเซอร์ที่มีค่า 1 ทั้งหมดได้โดยการเรียกใช้ ones

In [ ]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

เรามักต้องการสุ่มตัวอย่างแต่ละองค์ประกอบแบบสุ่ม (และไม่ขึ้นต่อกัน) จากฟังก์ชันการแจกแจงความน่าจะเป็นที่กำหนด ตัวอย่างเช่น พารามิเตอร์ของเครือข่ายประสาทมักเริ่มต้นแบบสุ่ม สนิปเป็ตต่อไปนี้สร้างเทนเซอร์ที่มีองค์ประกอบที่วาดจากฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ) โดยมีค่าเฉลี่ย 0 และส่วนเบี่ยงเบนมาตรฐาน 1

In [ ]:
import torch

# Create a tensor of elements drawn from a standard Gaussian distribution
X = torch.randn((2, 3, 4))

# Print the tensor
print(X)


tensor([[[ 7.9948e-01, -5.8139e-01, -2.6846e-01,  6.2386e-01],
         [-5.6546e-01,  1.7168e+00,  6.3314e-01,  1.1047e+00],
         [ 1.1252e-03, -1.2404e+00,  1.0591e+00,  2.8100e-01]],

        [[ 7.8367e-01,  2.8471e-01, -1.9310e+00,  3.3191e-01],
         [-1.7737e-01,  1.2246e+00, -1.7026e-01, -5.4285e-01],
         [ 1.5949e+00,  4.5789e-01,  5.9535e-01,  1.5532e-02]]])


**คำศัพท์:**

* Random sample: การสุ่มตัวอย่าง
* Independently: ไม่ขึ้นต่อกัน
* Probability distribution: ฟังก์ชันการแจกแจงความน่าจะเป็น
* Neural network parameters: พารามิเตอร์ของเครือข่ายประสาท
* Standard Gaussian distribution: ฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ)
* Mean: ค่าเฉลี่ย
* Standard deviation: ส่วนเบี่ยงเบนมาตรฐาน


ช่ครับ ในที่สุด เราก็สามารถสร้างเทนเซอร์ได้โดยการให้ค่าที่แน่นอนสำหรับแต่ละองค์ประกอบโดยการให้รายการ (อาจซ้อนกันได้) ของ Python list(s) ที่มีค่าตัวเลข ในที่นี้ เราสร้างเมทริกซ์ที่มีรายการของรายการ โดยที่รายการนอกสุดสอดคล้องกับแกน 0 และรายการด้านในสอดคล้องกับแกน 1

In [ ]:
import torch

# Create a matrix with a list of lists
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# Print the tensor
print(X)
print(Y)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [ ]:
X.shape

torch.Size([2, 3])

In [ ]:
Y.shape

torch.Size([3, 4])

2.1.2 Indexing and Slicing

ถูกแล้วครับ ดังเช่น Python lists เราสามารถเข้าถึงองค์ประกอบของเทนเซอร์ได้โดยการทำดัชนี (เริ่มต้นที่ 0) เพื่อเข้าถึงองค์ประกอบโดยอิงตามตำแหน่งขององค์ประกอบนั้นเมื่อเทียบกับส่วนท้ายของรายการ เราสามารถใช้การทำดัชนีแบบลบได้ ในที่สุด เราสามารถเข้าถึงช่วงทั้งหมดของดัชนีผ่านการตัดแบ่ง (เช่น X[start:stop]) โดยค่าที่ส่งกลับจะรวมดัชนีแรก (start) แต่ไม่รวมดัชนีสุดท้าย (stop) ในที่สุด เมื่อระบุดัชนีหรือการตัดแบ่งเพียงอันเดียวสำหรับเทนเซอร์อันดับ k จะถูกนำไปใช้ตามแกน 0 ดังนั้น ในโค้ดต่อไปนี้ [-1] จะเลือกแถวสุดท้าย และ [1:3] จะเลือกแถวที่สองและสาม

In [ ]:
X = torch.arange(12, dtype=torch.float32)
X = X.reshape(3,4)

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access the last row using negative indexing
last_row = X[-1]

# Print the last row
print(last_row)

# Access the second and third rows using slicing
second_and_third_rows = X[1:3]

# Print the second and third rows
print(second_and_third_rows)

tensor([4, 5, 6])
tensor([[4, 5, 6]])


In [ ]:
X[1][2]

tensor(6)

In [ ]:
X[1,2]

tensor(6.)

ใช่ครับ นอกเหนือจากการอ่านองค์ประกอบของเมทริกซ์แล้ว เรายังสามารถเขียนองค์ประกอบของเมทริกซ์ได้โดยการระบุดัชนี

In [ ]:
X[1, 2] = 17

In [ ]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
#หรือ
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set the element at (1, 2) to 10
X[1, 2] = 10

# Print the matrix
print(X)

tensor([[ 1,  2,  3],
        [ 4,  5, 10]])


เราสามารถใช้การทำดัชนีและการตัดแบ่งเพื่อกำหนดช่วงขององค์ประกอบให้กับค่าใหม่ได้ ตัวอย่างเช่น โค้ดต่อไปนี้จะตั้งค่าองค์ประกอบทั้งหมดในแถวที่สองให้เป็น 7:

In [ ]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set all the elements in the second row to 7
X[1, :] = 7

# Print the matrix
print(X)


tensor([[1, 2, 3],
        [7, 7, 7]])


In [ ]:
R = torch.arange(50,dtype=torch.float).reshape(5,10)
R

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [ ]:
R[0,:] = 111
R[2,:] = 33
R

tensor([[111., 111., 111., 111., 111., 111., 111., 111., 111., 111.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
        [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.],
        [ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
        [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.]])

2.1.3 Operations

ใช่ครับ ตอนนี้ที่เรารู้วิธีสร้างเทนเซอร์และวิธีอ่านและเขียนองค์ประกอบของเทนเซอร์แล้ว เราสามารถเริ่มจัดการเทนเซอร์ด้วยการดำเนินการทางคณิตศาสตร์ต่างๆ ได้แล้ว การดำเนินการที่เป็นประโยชน์ที่สุดประการหนึ่งคือการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ (elementwise operations) การดำเนินการเหล่านี้ใช้การดำเนินการสเกลาร์มาตรฐานกับแต่ละองค์ประกอบของเทนเซอร์ สำหรับฟังก์ชันที่ใช้เทนเซอร์สองตัวเป็นอินพุต การดำเนินการแบบองค์ประกอบต่อองค์ประกอบจะใช้ตัวดำเนินการไบนารีมาตรฐานกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกัน

เราสามารถสร้างฟังก์ชันแบบองค์ประกอบต่อองค์ประกอบจากฟังก์ชันใดก็ได้ที่แมปจากสเกลาร์เป็นสเกลาร์

ในสัญกรณ์ทางคณิตศาสตร์ เราใช้เครื่องหมาย 𝑓 : R → R เพื่อแสดงตัวดำเนินการสเกลาร์แบบยูนารี (รับอินพุตหนึ่งตัว) ซึ่งหมายความว่าฟังก์ชันนี้แมปจากจำนวนจริงใด ๆ ไปยังจำนวนจริงอื่น ๆ ตัวดำเนินการส่วนใหญ่ รวมถึงตัวดำเนินการแบบยูนารีเช่น 𝑒
𝑥
สามารถใช้แบบองค์ประกอบต่อองค์ประกอบได้

ตัวอย่างการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ ได้แก่:

* การบวก (+): C[i, j] = A[i, j] + B[i, j]
* การลบ (-): C[i, j] = A[i, j] - B[i, j]
* การคูณ (*): C[i, j] = A[i, j] * B[i, j]
* การหาร (/): C[i, j] = A[i, j] / B[i, j]
* การยกกำลัง (^): C[i, j] = A[i, j] ^ B[i, j]
* ฟังก์ชันตรีโกณมิติ: C[i, j] = sin(A[i, j])
* ฟังก์ชันการกระจายปกติแบบสะสม: C[i, j] = torch.distributions.Normal(0, 1).cdf(A[i, j])

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเทคนิคที่ทรงพลังในการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อประยุกต์การดำเนินการทางคณิตศาสตร์กับข้อมูลของเราได้อย่างมีประสิทธิภาพ

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
Z = X + Y

# Print the result
print(Z)


tensor([5, 7, 9])


In [ ]:
X = torch.arange(10,dtype = torch.float).reshape(2,5)
torch.exp(X)


tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]])

ใช่ครับ ในทำนองเดียวกัน เราแสดงตัวดำเนินการสเกลาร์แบบไบนารี ซึ่งแมปคู่ของจำนวนจริงไปเป็นจำนวนจริง (ตัวเดียว) ผ่านเครื่องหมาย 𝑓 : R, R → R ในกรณีที่เวกเตอร์ u และ v สองตัวมีรูปร่างเดียวกัน และตัวดำเนินการแบบไบนารี 𝑓 เราสามารถสร้างเวกเตอร์ c = 𝐹(u, v) ได้โดยการตั้งค่า 𝑐𝑖 ← 𝑓 (𝑢𝑖
, 𝑣𝑖) สำหรับทุก 𝑖 โดยที่ 𝑐𝑖
, 𝑢𝑖
และ 𝑣𝑖 เป็นองค์ประกอบที่ 𝑖 ของเวกเตอร์ c, u และ v

ที่นี่ เราสร้างเวกเตอร์ที่ได้ค่าของ 𝐹 : R
𝑑
, R
𝑑 → R
𝑑 โดยการยกฟังก์ชันสเกลาร์ให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเวกเตอร์ ตัวดำเนินการเลขคณิตมาตรฐานทั่วไปสำหรับการบวก (+), การลบ (-), การคูณ (*), การหาร (/) และการยกกำลัง (**) มีการยกให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง

**ตัวอย่าง**

```python
import torch

# Create two vectors
u = torch.tensor([1, 2, 3])
v = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
c = u + v

# Print the result
print(c)
```

Output:

```
tensor([5, 7, 9])
```

ในตัวอย่างนี้ เราใช้ตัวดำเนินการบวกแบบองค์ประกอบต่อองค์ประกอบกับสองเวกเตอร์เพื่อสร้างเวกเตอร์ใหม่ที่มีองค์ประกอบที่สอดคล้องกันของเวกเตอร์ u และ v เพิ่มเข้าด้วยกัน

เราสามารถใช้การดำเนินการแบบองค์ประกอบต่อองค์ประกอบกับฟังก์ชันที่ซับซ้อนกว่าได้เช่นกัน ตัวอย่างเช่น โค้ดต่อไปนี้จะใช้ฟังก์ชันดอทผลิตกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกันของสองเทนเซอร์ X และ Y:

```python
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the dot product function elementwise
c = torch.dot(X, Y)

# Print the result
print(c)
```

Output:

```
tensor(32)
```

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเครื่องมือที่ทรงพลังสำหรับการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อดำเนินการทางคณิตศาสตร์ที่หลากหลายกับเทนเซอร์ของเรา

**คำศัพท์:**

* Binary scalar operator: ตัวดำเนินการสเกลาร์แบบไบนารี
* Identically-shaped tensors: เทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง
* Vector-valued: ได้ค่าเป็นเวกเตอร์
* Lift: ยก

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

ใช่ครับ นอกเหนือจากการคำนวณแบบองค์ประกอบต่อองค์ประกอบแล้ว เรายังสามารถดำเนินการพีชคณิตเชิงเส้น เช่น ผลคูณจุดและการคูณเมทริกซ์ เราจะอธิบายเพิ่มเติมในหัวข้อ 2.3

เรายังสามารถรวมเทนเซอร์หลาย ๆ ตัวเข้าด้วยกัน โดยวางซ้อนกันแบบต่อเนื่องเพื่อสร้างเทนเซอร์ขนาดใหญ่กว่า เพียงแค่เราต้องระบุรายการของเทนเซอร์และบอกระบบตามแกนใดที่จะเชื่อมต่อ ตัวอย่างด้านล่างแสดงสิ่งที่เกิดขึ้นเมื่อเรารวมเมทริกซ์สองตัวเข้าด้วยกันตามแถว (แกน 0) แทนที่จะเป็นคอลัมน์ (แกน 1) เราจะเห็นว่าความยาวแกน 0 ของเอาต์พุตแรก (6) เป็นผลรวมของความยาวแกน 0 ของเทนเซอร์อินพุตทั้งสอง (3 + 3); ในขณะที่ความยาวแกน 1 ของเอาต์พุตที่สอง (8) เป็นผลรวมของความยาวแกน 1 ของเทนเซอร์อินพุตทั้งสอง (4 + 4)

**ตัวอย่าง**

```python
import torch

# Create two matrices
X = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
Y = torch.tensor([[9, 10, 11, 12], [13, 14, 15, 16]])

# Concatenate the matrices along rows
Z = torch.cat((X, Y), dim=0)

# Print the result
print(Z)
```

Output:

```
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]])
```

**คำศัพท์:**

* Concatenate: รวมเข้าด้วยกัน
* Stack: วางซ้อน
* Axis: แกน

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [2]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
Z

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [4]:
type(Z)

tuple

In [5]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
X.sum()

tensor(66.)

2.1.4 Broadcasting

ตอนนี้คุณทราบวิธีการดำเนินการกับตัวดำเนินการไบนารีแบบองค์ประกอบต่อองค์ประกอบบนเทนเซอร์สองตัวที่มีรูปร่างเดียวกันแล้ว ภายใต้เงื่อนไขบางประการ แม้ว่ารูปร่างจะแตกต่างกัน เราก็ยังสามารถดำเนินการกับตัวดำเนินการไบนารีแบบองค์ประกอบต่อองค์ประกอบได้โดยใช้กลไกการกระจายเสียง การกระจายเสียงทำงานตามขั้นตอนสองขั้นตอนต่อไปนี้: (1) ขยายอาร์เรย์หนึ่งหรือทั้งสองอาร์เรย์โดยการคัดลอกองค์ประกอบตามแกนที่มีความยาว 1 เพื่อให้หลังจากการแปลงนี้ เทนเซอร์ทั้งสองมีรูปร่างเดียวกัน; (2) ดำเนินการกับตัวดำเนินการแบบองค์ประกอบต่อองค์ประกอบบนอาร์เรย์ที่ได้

In [9]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [10]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([5])

# กระจายเสียง array b เพื่อให้มีขนาดเดียวกับ array a
b_broadcast = np.broadcast_to(b, a.shape)

# บวก array a และ b_broadcast
c = a + b_broadcast

print(c)
print(b_broadcast)

[6 7 8]
[5 5 5]


In [12]:
a+b

array([6, 7, 8])

2.1.5 Saving Memory

การรันการดำเนินการอาจทำให้มีการจัดสรรหน่วยความจำใหม่เพื่อโฮสต์ผลลัพธ์ ตัวอย่างเช่น ถ้าเราเขียน Y = X + Y เราจะยกเลิกการอ้างอิงเทนเซอร์ที่ Y เคยชี้ไปที่และชี้ Y ไปที่หน่วยความจำที่จัดสรรใหม่ เราสามารถแสดงปัญหานี้ได้ด้วยฟังก์ชัน id() ของ Python ซึ่งให้ที่อยู่ที่แน่นอนของอ็อบเจ็กต์ที่อ้างอิงในหน่วยความจำ โปรดทราบว่าหลังจากเราเรียกใช้ Y = Y + X, id(Y) จะชี้ไปที่ตำแหน่งที่แตกต่างกัน นั่นเป็นเพราะ Python ประเมิน Y + X ก่อน จัดสรรหน่วยความจำใหม่สำหรับผลลัพธ์ แล้วจึงชี้ Y ไปที่ตำแหน่งใหม่นี้ในหน่วยความจำ

ตัวอย่างต่อไปนี้แสดงวิธีใช้ฟังก์ชัน id() เพื่อแสดงปัญหาการจัดสรรหน่วยความจำ:

In [13]:
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# พิมพ์ id ของ Y
print(id(Y))

# บวก X และ Y
Y = Y + X

# พิมพ์ id ของ Y อีกครั้ง
print(id(Y))


136223366371472
136223366373200


โชคดีที่การทำ in-place operations นั้นง่ายมาก เราสามารถกำหนดผลลัพธ์ของการดำเนินการให้กับอาร์เรย์ Y ที่จัดสรรไว้ก่อนหน้านี้โดยใช้ slice notation: Y[:] = <expression>

เพื่ออธิบายแนวคิดนี้ เราได้เขียนทับค่าของเทนเซอร์ Z หลังจากทำการ 초기화โดยใช้ zeros_like เพื่อให้มีรูปร่างเดียวกันกับ Y

ตัวอย่างต่อไปนี้แสดงวิธีใช้ slice notation เพื่อทำ in-place operations:

In [18]:
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# สร้างเทนเซอร์ Z
Z = np.zeros_like(Y)

# บวก X และ Y แบบ in-place
Y[:] = X + Y

# พิมพ์ค่าของ Y
print(Y)
#ตามที่คุณเห็น ค่าของ Y ได้ถูกเปลี่ยนเป็น [5, 7, 9] แบบ in-place โดยไม่จัดสรรหน่วยความจำใหม่



[5 7 9]


ตามที่คุณเห็น id ของ Y เปลี่ยนไปหลังจากที่เราเรียกใช้ Y = Y + X นั่นเป็นเพราะ Python ได้จัดสรรหน่วยความจำใหม่สำหรับผลลัพธ์

ปัญหานี้สามารถแก้ไขได้โดยใช้เทคนิคที่เรียกว่า "in-place operations" In-place operations ทำการคำนวณบนเทนเซอร์เดียวกันโดยหลีกเลี่ยงการจัดสรรหน่วยความจำใหม่ ตัวอย่างเช่น ใน PyTorch เราสามารถใช้ฟังก์ชัน add_() เพื่อบวก X และ Y แบบ in-place:

In [16]:
import torch

# สร้างเทนเซอร์
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])
print(id(Y))
# บวก X และ Y แบบ in-place
Y.add_(X)

# พิมพ์ id ของ Y
print(id(Y))
print(Y)

136223366386752
136223366386752
tensor([5, 7, 9])


In [17]:
before = id(Y)
Y = Y + X
id(Y) == before


False

ตามที่คุณเห็น id ของ Y ไม่ได้เปลี่ยนไปหลังจากที่เราเรียกใช้ Y.add_(X) นั่นเป็นเพราะ PyTorch ได้ทำการคำนวณบนเทนเซอร์ Y เดิมโดยไม่จัดสรรหน่วยความจำใหม่

การใช้ in-place operations สามารถช่วยลดการใช้หน่วยความจำและปรับปรุงประสิทธิภาพของโปรแกรมของคุณ อย่างไรก็ตาม สิ่งสำคัญคือต้องใช้ in-place operations อย่างระมัดระวัง เพราะอาจนำไปสู่ผลลัพธ์ที่ไม่คาดคิดได้




ถ้าค่าของ X ไม่ได้ถูกนำมาใช้ซ้ำในคำนวณถัดไป เราก็สามารถใช้ X[:] = X + Y หรือ X += Y เพื่อลดค่าใช้จ่ายหน่วยความจำของการดำเนินการ

X[:] = X + Y เป็นการกำหนดผลลัพธ์ของ X + Y ให้กับเทนเซอร์ X แบบ in-place ในขณะที่ X += Y เป็นการกำหนดผลลัพธ์ของ X + Y ให้กับเทนเซอร์ X แบบ in-place เช่นกัน แต่ X += Y เป็นคำสั่งที่อ่านง่ายกว่า

In [20]:
#ตัวอย่างต่อไปนี้แสดงวิธีใช้ X[:] = X + Y และ X += Y เพื่อทำ in-place
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

before = id(X)
# บวก X และ Y แบบ in-place โดยใช้ X[:] = X + Y
X[:] = X + Y
print(id(X) == before)
# พิมพ์ค่าของ X
print(X)
id(X) == before
# บวก X และ Y แบบ in-place โดยใช้ X += Y
X += Y
print(id(X) == before)
# พิมพ์ค่าของ X อีกครั้ง
print(X)


True
[5 7 9]
True
[ 9 12 15]


2.1.6 Conversion to Other Python Objects


การแปลของข้อความที่คุณให้มานั้นเป็นดังนี้:

การแปลงเป็น NumPy tensor (ndarray) หรือ vice versa นั้นง่ายมาก เทนเซอร์ PyTorch และอาร์เรย์ NumPy จะแชร์หน่วยความจำพื้นฐานของตนเอง และการเปลี่ยนแปลงหนึ่งผ่านการดำเนินการ in-place จะเปลี่ยนแปลงอีกอันหนึ่งด้วยเช่นกัน

ตัวอย่างต่อไปนี้แสดงวิธีแปลงเทนเซอร์ PyTorch เป็นอาร์เรย์ NumPy และ vice versa:

In [24]:
import torch
import numpy as np

# สร้างเทนเซอร์ PyTorch
x = torch.tensor([1, 2, 3])

# แปลงเทนเซอร์ PyTorch เป็นอาร์เรย์ NumPy
y = x.numpy()

# พิมพ์ค่าของ y
print(y)

# แปลงอาร์เรย์ NumPy เป็นเทนเซอร์ PyTorch
z = torch.from_numpy(y)

# พิมพ์ค่าของ z
print(z)
type(x),type(y),type(z)

[1 2 3]
tensor([1, 2, 3])


(torch.Tensor, numpy.ndarray, torch.Tensor)

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)


(tensor([3.5000]), 3.5, 3.5, 3)

2.1.8 Exercises

1. รันโค้ดในส่วนนี้ เปลี่ยนเงื่อนไข X == Y เป็น X < Y หรือ X > Y แล้วดูว่าคุณจะได้เทนเซอร์แบบใด

In [34]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([1, 2, 3])
Y = torch.tensor([2, 3, 4])

# สร้างเงื่อนไข X < Y หรือ X > Y
condition = X < Y

# พิมพ์ค่าของ condition
print(f"X < Y จะให้เทนเซอร์ต่อไปนี้:\n{condition}")


X < Y จะให้เทนเซอร์ต่อไปนี้:
tensor([True, True, True])


In [33]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([1, 2, 3])
Y = torch.tensor([2, 3, 4])

# สร้างเงื่อนไข X < Y หรือ X > Y
condition = X > Y

# พิมพ์ค่าของ condition
print(f" X > Y จะให้เทนเซอร์ต่อไปนี้:\n{condition}")


 X > Y จะให้เทนเซอร์ต่อไปนี้:
tensor([False, False, False])


2. แทนที่เทนเซอร์ทั้งสองที่ดำเนินการแบบองค์ประกอบต่อองค์ประกอบในกลไกการกระจายเสียงด้วยรูปร่างอื่น เช่น เทนเซอร์สามมิติ ผลลัพธ์จะเหมือนกับที่คาดไว้หรือไม่

In [35]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Y = torch.tensor([1, 2, 3])

# กระจายเสียงเทนเซอร์ Y เพื่อให้มีรูปร่างเดียวกันกับเทนเซอร์ X
Y_broadcast = Y.unsqueeze(0).unsqueeze(0).expand_as(X)

# บวกเทนเซอร์ X และ Y_broadcast แบบองค์ประกอบต่อองค์ประกอบ
Z = X + Y

# พิมพ์ค่าของ Z
print(Z)


tensor([[[ 2,  4,  6],
         [ 5,  7,  9]],

        [[ 8, 10, 12],
         [11, 13, 15]]])


In [36]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Y = torch.tensor([1, 2, 3])

# กระจายเสียงเทนเซอร์ Y เพื่อให้มีรูปร่างเดียวกันกับเทนเซอร์ X
Y_broadcast = Y.unsqueeze(0).unsqueeze(0).expand_as(X)

# บวกเทนเซอร์ X และ Y_broadcast แบบองค์ประกอบต่อองค์ประกอบ
Z = X + Y_broadcast

# พิมพ์ค่าของ Z
print(Z)


tensor([[[ 2,  4,  6],
         [ 5,  7,  9]],

        [[ 8, 10, 12],
         [11, 13, 15]]])


ตามที่คุณเห็น เทนเซอร์ Z มีรูปร่างเดียวกันกับเทนเซอร์ X และค่าของแต่ละองค์ประกอบของ Z เป็นผลลัพธ์ของการบวกองค์ประกอบที่สอดคล้องกันของ X และ Y_broadcast

กลไกการกระจายเสียงเป็นเครื่องมือที่ทรงพลังที่ช่วยให้เราสามารถดำเนินการกับเทนเซอร์ที่มีรูปร่างต่างๆ ได้อย่างง่ายดาย โดยไม่ต้องใช้ลูป

# 2.2 Data Preprocessing

การแปลของข้อความที่คุณให้มานั้นเป็นดังนี้:

จนถึงตอนนี้ เราได้ทำงานกับข้อมูลสังเคราะห์ที่อยู่ในเทนเซอร์สำเร็จรูป อย่างไรก็ตาม ในการนำการเรียนรู้เชิงลึกไปใช้ในโลกแห่งความจริง เราต้องดึงข้อมูลที่สกปรกซึ่งเก็บอยู่ในรูปแบบต่างๆ และทำการประมวลผลก่อนล่วงหน้าเพื่อให้เหมาะสมกับความต้องการของเรา โชคดีที่ไลบรารี pandas สามารถช่วยยกของหนักๆ ให้เราได้ แม้ว่าส่วนนี้จะไม่ใช่การสอน pandas อย่างเหมาะสม แต่ก็จะให้บทเรียนเร่งรัดเกี่ยวกับฟังก์ชันการทำงานทั่วไปบางอย่าง

ไลบรารี pandas เป็นไลบรารี Python ที่ใช้สำหรับการวิเคราะห์และการจัดการข้อมูล มันมีโครงสร้างข้อมูลที่มีประสิทธิภาพสำหรับจัดเก็บและประมวลผลข้อมูลขนาดใหญ่ นอกจากนี้ยังมีเครื่องมือสำหรับการทำความสะอาดข้อมูล การรวมกลุ่ม และการแปลงข้อมูล

ฟังก์ชันการทำงานทั่วไปบางอย่างของ pandas ได้แก่:

* การอ่านและเขียนข้อมูลจาก/ไปยังไฟล์ต่างๆ เช่น CSV, Excel และ JSON
* การเลือกและกรองข้อมูล
* การรวมข้อมูลจากหลายแหล่ง
* การเติมเต็มค่าที่หายไป
* การแปลงประเภทข้อมูล
* การสร้างฟีเจอร์ใหม่

ในส่วนนี้ เราจะกล่าวถึงฟังก์ชันการทำงานบางอย่างของ pandas ที่มีประโยชน์สำหรับการประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก ตัวอย่างเช่น เราสามารถใช้ pandas เพื่อ:

* อ่านข้อมูลจากไฟล์ CSV และแปลงเป็นเทนเซอร์
* กรองข้อมูลที่ไม่สมบูรณ์หรือผิดปกติออก
* แปลงประเภทข้อมูลของคอลัมน์ต่างๆ ให้เหมาะสมกับการเรียนรู้เชิงลึก
* สร้างฟีเจอร์ใหม่จากข้อมูลที่มีอยู่

ต่อไปนี้เป็นตัวอย่างของการใช้ pandas เพื่อประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก:

```python
import pandas as pd

# อ่านข้อมูลจากไฟล์ CSV
df = pd.read_csv('data.csv')

# กรองข้อมูลที่ไม่สมบูรณ์หรือผิดปกติออก
df = df.dropna()
df = df[df['price'] > 0]

# แปลงประเภทข้อมูลของคอลัมน์ต่างๆ ให้เหมาะสมกับการเรียนรู้เชิงลึก
df['price'] = pd.to_numeric(df['price'])
df['category'] = pd.get_dummies(df['category'])

# สร้างฟีเจอร์ใหม่จากข้อมูลที่มีอยู่
df['feature_1'] = df['price'] * df['quantity']

# แปลงข้อมูลเป็นเทนเซอร์
X = df[['feature_1', 'category']].to_numpy()
y = df['price'].to_numpy()
```

ข้อมูลในเทนเซอร์ X และ y พร้อมสำหรับการใช้ในโมเดลการเรียนรู้เชิงลึกแล้ว

ไลบรารี pandas เป็นเครื่องมือที่ทรงพลังสำหรับการประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก หากคุณกำลังทำงานกับข้อมูลจริง ขอแนะนำให้คุณศึกษาเกี่ยวกับ pandas เพิ่มเติม

In [43]:
import os

# เชื่อมต่อ Google Drive กับ Google Colab


# เก็บไฟล์ house_tiny.csv ไว้ที่ตัวแปร data_file
data_file = '/content/drive/My Drive/house_tiny.csv'


In [44]:
import os

# สร้างไดเร็กทอรี data ถ้ายังไม่มีอยู่
os.makedirs(os.path.join('..', 'data'), exist_ok=True)

# สร้างไฟล์ house_tiny.csv ในไดเร็กทอรี data
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# เขียนข้อมูลไปยังไฟล์ house_tiny.csv
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [45]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [47]:
data.isnull().sum()

NumRooms    2
RoofType    3
Price       0
dtype: int64

In [48]:
data.shape

(4, 3)