<a href="https://colab.research.google.com/github/surapitttha/Deep-Learning-/blob/main/deep_learning_2_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีทักษะการเอาชีวิตรอดบางประการ ได้แก่:

(i) เทคนิคสำหรับการจัดเก็บและจัดการข้อมูล
(ii) ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
(iii) ความรู้เกี่ยวกับการดำเนินการพีชคณิตเชิงเส้นพื้นฐานที่เราใช้กับองค์ประกอบข้อมูลมิติสูง
(iv) แคลคูลัสเพียงพอที่จะกำหนดทิศทางในการปรับพารามิเตอร์แต่ละตัวเพื่อลดฟังก์ชันการสูญเสีย
(v) ความสามารถในการคำนวณอนุพันธ์โดยอัตโนมัติเพื่อให้คุณลืมแคลคูลัสที่คุณเพิ่งเรียนรู้ไปได้มาก
(vi) ความเข้าใจพื้นฐานเกี่ยวกับความน่าจะเป็น ซึ่งเป็นภาษาหลักของเราสำหรับการใช้เหตุผลภายใต้ความไม่แน่นอน
(vii) ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการเมื่อคุณติดขัด

โดยสรุป บทนี้จะให้คำแนะนำเบื้องต้นอย่างรวดเร็วเกี่ยวกับพื้นฐานที่คุณจำเป็นต้องรู้เพื่อติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้

**สรุป**

ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีพื้นฐานในด้านต่อไปนี้:

* เทคนิคการจัดเก็บและจัดการข้อมูล
* ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
* พีชคณิตเชิงเส้นพื้นฐาน
* แคลคูลัสพื้นฐาน
* การคำนวณอนุพันธ์โดยอัตโนมัติ
* ความน่าจะเป็น
* ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการ

บทนี้จะให้คำแนะนำเบื้องต้นเกี่ยวกับพื้นฐานเหล่านี้ เพื่อให้คุณสามารถติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้ได้

#2.1 Data Manipulation


## 2.1.1 Getting Started

To start, we import the PyTorch library. Note that the package name is torch.


In [ ]:
import torch

**การแปลและเรียบเรียง**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ในกรณีหนึ่งมิติ นั่นคือ เมื่อมีเพียงแกนเดียว เราจะเรียก tensor ว่าเวกเตอร์ ด้วยแกนสองแกน Tensor จะเรียกว่าเมทริกซ์ ด้วยแกนมากกว่า 2 แกน เราจะลบชื่อเฉพาะออกและเรียกวัตถุนี้ว่าเทนเซอร์อันดับ k

PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า ตัวอย่างเช่น ด้วยการเรียกใช้ arange(n) เราสามารถสร้างเวกเตอร์ของค่าที่มีระยะห่างเท่ากัน โดยเริ่มต้นที่ 0 (รวม) และสิ้นสุดที่ n (ไม่รวม) โดยค่าเริ่มต้น ขนาดของช่วงคือ 1 เว้นแต่จะระบุไว้เป็นอย่างอื่น เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**สรุป**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ใน PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**คำศัพท์:**

* Tensor: เทนเซอร์
* Array: อาร์เรย์
* Dimension: มิติ
* Vector: เวกเตอร์
* Matrix: เมทริกซ์
* Order: อันดับ
* Main memory: หน่วยความจำหลัก
* CPU-based computation: การคำนวณบน CPU

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

ค่าแต่ละค่าในเทนเซอร์เรียกว่าองค์ประกอบของเทนเซอร์ เทนเซอร์ x มี 12 องค์ประกอบ

เราสามารถตรวจสอบจำนวนองค์ประกอบทั้งหมดในเทนเซอร์ผ่านเมธอด numel ของเทนเซอร์ดังกล่าว

In [ ]:
x.numel()

12

เราสามารถเข้าถึงรูปร่างของเทนเซอร์ (ความยาวตามแต่ละแกน) โดยการตรวจสอบแอตทริบิวต์ shape ของเทนเซอร์นั้น เนื่องจากเรากำลังจัดการกับเวกเตอร์ที่นี่ รูปร่างจึงมีเพียงองค์ประกอบเดียวและเหมือนกับขนาด

In [ ]:
x.shape

torch.Size([12])


การแปลภาษา

เราสามารถเปลี่ยนรูปร่างของเทนเซอร์ได้โดยไม่เปลี่ยนแปลงขนาดหรือค่าของเทนเซอร์นั้น โดยการเรียกใช้ reshape ตัวอย่างเช่น เราสามารถแปลงเวกเตอร์ x ที่มีรูปร่าง (12,) เป็นเมทริกซ์ X ที่มีรูปร่าง (3, 4) ได้ เทนเซอร์ใหม่นี้จะเก็บองค์ประกอบทั้งหมดไว้ แต่จัดเรียงใหม่เป็นเมทริกซ์ โปรดสังเกตว่าองค์ประกอบของเวกเตอร์ของเราจะถูกวางเรียงทีละแถว ดังนั้น x[3] == X[0, 3]

In [ ]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

โปรดสังเกตว่าการระบุทุกองค์ประกอบของรูปร่างเพื่อ reshape เป็นสิ่งที่ไม่จำเป็น เนื่องจากเรารู้ขนาดของเทนเซอร์ของเราอยู่แล้ว เราสามารถคำนวณองค์ประกอบหนึ่งของรูปร่างได้โดยกำหนดส่วนที่เหลือ ตัวอย่างเช่น กำหนดเทนเซอร์ที่มีขนาด n และรูปร่างเป้าหมาย (h, w) เรารู้ว่า w = n/h เพื่ออนุมานองค์ประกอบหนึ่งของรูปร่างโดยอัตโนมัติ เราสามารถใส่ -1 สำหรับองค์ประกอบของรูปร่างที่ควรอนุมานโดยอัตโนมัติ ในกรณีของเรา แทนที่จะเรียก x.reshape(3, 4) เราอาจเรียก x.reshape(-1, 4) หรือ x.reshape(3, -1) ได้เทียบเท่ากัน

ผู้ปฏิบัติงานมักต้องทำงานกับเทนเซอร์ที่เริ่มต้นเพื่อให้มีค่า 0 หรือ 1 ทั้งหมด เราสามารถสร้างเทนเซอร์ที่มีองค์ประกอบทั้งหมดตั้งเป็น 0 และรูปร่างของ (2, 3, 4) ได้ผ่านฟังก์ชัน zeros

In [ ]:
x.reshape(4,-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
x.reshape(2,-1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.zeros(2,3,4).shape

torch.Size([2, 3, 4])

ในทำนองเดียวกัน เราสามารถสร้างเทนเซอร์ที่มีค่า 1 ทั้งหมดได้โดยการเรียกใช้ ones

In [ ]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

เรามักต้องการสุ่มตัวอย่างแต่ละองค์ประกอบแบบสุ่ม (และไม่ขึ้นต่อกัน) จากฟังก์ชันการแจกแจงความน่าจะเป็นที่กำหนด ตัวอย่างเช่น พารามิเตอร์ของเครือข่ายประสาทมักเริ่มต้นแบบสุ่ม สนิปเป็ตต่อไปนี้สร้างเทนเซอร์ที่มีองค์ประกอบที่วาดจากฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ) โดยมีค่าเฉลี่ย 0 และส่วนเบี่ยงเบนมาตรฐาน 1

In [ ]:
import torch

# Create a tensor of elements drawn from a standard Gaussian distribution
X = torch.randn((2, 3, 4))

# Print the tensor
print(X)


tensor([[[ 0.3770,  0.7283,  1.2330,  0.8085],
         [-0.5008, -1.0231, -0.2561, -1.8738],
         [ 1.7550,  1.9932, -0.3846, -0.7980]],

        [[ 0.5257,  0.8185, -1.0019,  0.5500],
         [ 0.2106, -1.2254,  0.2851, -1.1027],
         [ 0.8532, -0.1469, -0.9594, -0.3782]]])


**คำศัพท์:**

* Random sample: การสุ่มตัวอย่าง
* Independently: ไม่ขึ้นต่อกัน
* Probability distribution: ฟังก์ชันการแจกแจงความน่าจะเป็น
* Neural network parameters: พารามิเตอร์ของเครือข่ายประสาท
* Standard Gaussian distribution: ฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ)
* Mean: ค่าเฉลี่ย
* Standard deviation: ส่วนเบี่ยงเบนมาตรฐาน


ช่ครับ ในที่สุด เราก็สามารถสร้างเทนเซอร์ได้โดยการให้ค่าที่แน่นอนสำหรับแต่ละองค์ประกอบโดยการให้รายการ (อาจซ้อนกันได้) ของ Python list(s) ที่มีค่าตัวเลข ในที่นี้ เราสร้างเมทริกซ์ที่มีรายการของรายการ โดยที่รายการนอกสุดสอดคล้องกับแกน 0 และรายการด้านในสอดคล้องกับแกน 1

In [ ]:
import torch

# Create a matrix with a list of lists
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# Print the tensor
print(X)
print(Y)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [ ]:
X.shape

torch.Size([2, 3])

In [ ]:
Y.shape

torch.Size([3, 4])

## 2.1.2 Indexing and Slicing

ถูกแล้วครับ ดังเช่น Python lists เราสามารถเข้าถึงองค์ประกอบของเทนเซอร์ได้โดยการทำดัชนี (เริ่มต้นที่ 0) เพื่อเข้าถึงองค์ประกอบโดยอิงตามตำแหน่งขององค์ประกอบนั้นเมื่อเทียบกับส่วนท้ายของรายการ เราสามารถใช้การทำดัชนีแบบลบได้ ในที่สุด เราสามารถเข้าถึงช่วงทั้งหมดของดัชนีผ่านการตัดแบ่ง (เช่น X[start:stop]) โดยค่าที่ส่งกลับจะรวมดัชนีแรก (start) แต่ไม่รวมดัชนีสุดท้าย (stop) ในที่สุด เมื่อระบุดัชนีหรือการตัดแบ่งเพียงอันเดียวสำหรับเทนเซอร์อันดับ k จะถูกนำไปใช้ตามแกน 0 ดังนั้น ในโค้ดต่อไปนี้ [-1] จะเลือกแถวสุดท้าย และ [1:3] จะเลือกแถวที่สองและสาม

In [ ]:
X = torch.arange(12, dtype=torch.float32)
X = X.reshape(3,4)

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access the last row using negative indexing
last_row = X[-1]

# Print the last row
print(last_row)

# Access the second and third rows using slicing
second_and_third_rows = X[1:3]

# Print the second and third rows
print(second_and_third_rows)

tensor([4, 5, 6])
tensor([[4, 5, 6]])


In [ ]:
X[1][2]

tensor(6)

In [ ]:
X[1,2]

tensor(6)

ใช่ครับ นอกเหนือจากการอ่านองค์ประกอบของเมทริกซ์แล้ว เรายังสามารถเขียนองค์ประกอบของเมทริกซ์ได้โดยการระบุดัชนี

In [ ]:
X[1, 2] = 17

In [ ]:
X

tensor([[ 1,  2,  3],
        [ 4,  5, 17]])

In [ ]:
#หรือ
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set the element at (1, 2) to 10
X[1, 2] = 10

# Print the matrix
print(X)

tensor([[ 1,  2,  3],
        [ 4,  5, 10]])


เราสามารถใช้การทำดัชนีและการตัดแบ่งเพื่อกำหนดช่วงขององค์ประกอบให้กับค่าใหม่ได้ ตัวอย่างเช่น โค้ดต่อไปนี้จะตั้งค่าองค์ประกอบทั้งหมดในแถวที่สองให้เป็น 7:

In [ ]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set all the elements in the second row to 7
X[1, :] = 7

# Print the matrix
print(X)


tensor([[1, 2, 3],
        [7, 7, 7]])


In [ ]:
R = torch.arange(50,dtype=torch.float).reshape(5,10)
R

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [ ]:
R[0,:] = 111
R[2,:] = 33
R

tensor([[111., 111., 111., 111., 111., 111., 111., 111., 111., 111.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
        [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.],
        [ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
        [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.]])

## 2.1.3 Operations

ใช่ครับ ตอนนี้ที่เรารู้วิธีสร้างเทนเซอร์และวิธีอ่านและเขียนองค์ประกอบของเทนเซอร์แล้ว เราสามารถเริ่มจัดการเทนเซอร์ด้วยการดำเนินการทางคณิตศาสตร์ต่างๆ ได้แล้ว การดำเนินการที่เป็นประโยชน์ที่สุดประการหนึ่งคือการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ (elementwise operations) การดำเนินการเหล่านี้ใช้การดำเนินการสเกลาร์มาตรฐานกับแต่ละองค์ประกอบของเทนเซอร์ สำหรับฟังก์ชันที่ใช้เทนเซอร์สองตัวเป็นอินพุต การดำเนินการแบบองค์ประกอบต่อองค์ประกอบจะใช้ตัวดำเนินการไบนารีมาตรฐานกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกัน

เราสามารถสร้างฟังก์ชันแบบองค์ประกอบต่อองค์ประกอบจากฟังก์ชันใดก็ได้ที่แมปจากสเกลาร์เป็นสเกลาร์

ในสัญกรณ์ทางคณิตศาสตร์ เราใช้เครื่องหมาย 𝑓 : R → R เพื่อแสดงตัวดำเนินการสเกลาร์แบบยูนารี (รับอินพุตหนึ่งตัว) ซึ่งหมายความว่าฟังก์ชันนี้แมปจากจำนวนจริงใด ๆ ไปยังจำนวนจริงอื่น ๆ ตัวดำเนินการส่วนใหญ่ รวมถึงตัวดำเนินการแบบยูนารีเช่น 𝑒
𝑥
สามารถใช้แบบองค์ประกอบต่อองค์ประกอบได้

ตัวอย่างการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ ได้แก่:

* การบวก (+): C[i, j] = A[i, j] + B[i, j]
* การลบ (-): C[i, j] = A[i, j] - B[i, j]
* การคูณ (*): C[i, j] = A[i, j] * B[i, j]
* การหาร (/): C[i, j] = A[i, j] / B[i, j]
* การยกกำลัง (^): C[i, j] = A[i, j] ^ B[i, j]
* ฟังก์ชันตรีโกณมิติ: C[i, j] = sin(A[i, j])
* ฟังก์ชันการกระจายปกติแบบสะสม: C[i, j] = torch.distributions.Normal(0, 1).cdf(A[i, j])

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเทคนิคที่ทรงพลังในการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อประยุกต์การดำเนินการทางคณิตศาสตร์กับข้อมูลของเราได้อย่างมีประสิทธิภาพ

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
Z = X + Y

# Print the result
print(Z)


tensor([5, 7, 9])


In [ ]:
X = torch.arange(10,dtype = torch.float).reshape(2,5)
torch.exp(X)


tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]])

ใช่ครับ ในทำนองเดียวกัน เราแสดงตัวดำเนินการสเกลาร์แบบไบนารี ซึ่งแมปคู่ของจำนวนจริงไปเป็นจำนวนจริง (ตัวเดียว) ผ่านเครื่องหมาย 𝑓 : R, R → R ในกรณีที่เวกเตอร์ u และ v สองตัวมีรูปร่างเดียวกัน และตัวดำเนินการแบบไบนารี 𝑓 เราสามารถสร้างเวกเตอร์ c = 𝐹(u, v) ได้โดยการตั้งค่า 𝑐𝑖 ← 𝑓 (𝑢𝑖
, 𝑣𝑖) สำหรับทุก 𝑖 โดยที่ 𝑐𝑖
, 𝑢𝑖
และ 𝑣𝑖 เป็นองค์ประกอบที่ 𝑖 ของเวกเตอร์ c, u และ v

ที่นี่ เราสร้างเวกเตอร์ที่ได้ค่าของ 𝐹 : R
𝑑
, R
𝑑 → R
𝑑 โดยการยกฟังก์ชันสเกลาร์ให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเวกเตอร์ ตัวดำเนินการเลขคณิตมาตรฐานทั่วไปสำหรับการบวก (+), การลบ (-), การคูณ (*), การหาร (/) และการยกกำลัง (**) มีการยกให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง

**ตัวอย่าง**

```python
import torch

# Create two vectors
u = torch.tensor([1, 2, 3])
v = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
c = u + v

# Print the result
print(c)
```

Output:

```
tensor([5, 7, 9])
```

ในตัวอย่างนี้ เราใช้ตัวดำเนินการบวกแบบองค์ประกอบต่อองค์ประกอบกับสองเวกเตอร์เพื่อสร้างเวกเตอร์ใหม่ที่มีองค์ประกอบที่สอดคล้องกันของเวกเตอร์ u และ v เพิ่มเข้าด้วยกัน

เราสามารถใช้การดำเนินการแบบองค์ประกอบต่อองค์ประกอบกับฟังก์ชันที่ซับซ้อนกว่าได้เช่นกัน ตัวอย่างเช่น โค้ดต่อไปนี้จะใช้ฟังก์ชันดอทผลิตกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกันของสองเทนเซอร์ X และ Y:

```python
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the dot product function elementwise
c = torch.dot(X, Y)

# Print the result
print(c)
```

Output:

```
tensor(32)
```

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเครื่องมือที่ทรงพลังสำหรับการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อดำเนินการทางคณิตศาสตร์ที่หลากหลายกับเทนเซอร์ของเรา

**คำศัพท์:**

* Binary scalar operator: ตัวดำเนินการสเกลาร์แบบไบนารี
* Identically-shaped tensors: เทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง
* Vector-valued: ได้ค่าเป็นเวกเตอร์
* Lift: ยก

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

ใช่ครับ นอกเหนือจากการคำนวณแบบองค์ประกอบต่อองค์ประกอบแล้ว เรายังสามารถดำเนินการพีชคณิตเชิงเส้น เช่น ผลคูณจุดและการคูณเมทริกซ์ เราจะอธิบายเพิ่มเติมในหัวข้อ 2.3

เรายังสามารถรวมเทนเซอร์หลาย ๆ ตัวเข้าด้วยกัน โดยวางซ้อนกันแบบต่อเนื่องเพื่อสร้างเทนเซอร์ขนาดใหญ่กว่า เพียงแค่เราต้องระบุรายการของเทนเซอร์และบอกระบบตามแกนใดที่จะเชื่อมต่อ ตัวอย่างด้านล่างแสดงสิ่งที่เกิดขึ้นเมื่อเรารวมเมทริกซ์สองตัวเข้าด้วยกันตามแถว (แกน 0) แทนที่จะเป็นคอลัมน์ (แกน 1) เราจะเห็นว่าความยาวแกน 0 ของเอาต์พุตแรก (6) เป็นผลรวมของความยาวแกน 0 ของเทนเซอร์อินพุตทั้งสอง (3 + 3); ในขณะที่ความยาวแกน 1 ของเอาต์พุตที่สอง (8) เป็นผลรวมของความยาวแกน 1 ของเทนเซอร์อินพุตทั้งสอง (4 + 4)

**ตัวอย่าง**

```python
import torch

# Create two matrices
X = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
Y = torch.tensor([[9, 10, 11, 12], [13, 14, 15, 16]])

# Concatenate the matrices along rows
Z = torch.cat((X, Y), dim=0)

# Print the result
print(Z)
```

Output:

```
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]])
```

**คำศัพท์:**

* Concatenate: รวมเข้าด้วยกัน
* Stack: วางซ้อน
* Axis: แกน

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [ ]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
Z

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
type(Z)

tuple

In [ ]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum()

tensor(66.)

## 2.1.4 Broadcasting

ตอนนี้คุณทราบวิธีการดำเนินการกับตัวดำเนินการไบนารีแบบองค์ประกอบต่อองค์ประกอบบนเทนเซอร์สองตัวที่มีรูปร่างเดียวกันแล้ว ภายใต้เงื่อนไขบางประการ แม้ว่ารูปร่างจะแตกต่างกัน เราก็ยังสามารถดำเนินการกับตัวดำเนินการไบนารีแบบองค์ประกอบต่อองค์ประกอบได้โดยใช้กลไกการกระจายเสียง การกระจายเสียงทำงานตามขั้นตอนสองขั้นตอนต่อไปนี้: (1) ขยายอาร์เรย์หนึ่งหรือทั้งสองอาร์เรย์โดยการคัดลอกองค์ประกอบตามแกนที่มีความยาว 1 เพื่อให้หลังจากการแปลงนี้ เทนเซอร์ทั้งสองมีรูปร่างเดียวกัน; (2) ดำเนินการกับตัวดำเนินการแบบองค์ประกอบต่อองค์ประกอบบนอาร์เรย์ที่ได้

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([5])

# กระจายเสียง array b เพื่อให้มีขนาดเดียวกับ array a
b_broadcast = np.broadcast_to(b, a.shape)

# บวก array a และ b_broadcast
c = a + b_broadcast

print(c)
print(b_broadcast)

[6 7 8]
[5 5 5]


In [ ]:
a+b

array([6, 7, 8])

## 2.1.5 Saving Memory

การรันการดำเนินการอาจทำให้มีการจัดสรรหน่วยความจำใหม่เพื่อโฮสต์ผลลัพธ์ ตัวอย่างเช่น ถ้าเราเขียน Y = X + Y เราจะยกเลิกการอ้างอิงเทนเซอร์ที่ Y เคยชี้ไปที่และชี้ Y ไปที่หน่วยความจำที่จัดสรรใหม่ เราสามารถแสดงปัญหานี้ได้ด้วยฟังก์ชัน id() ของ Python ซึ่งให้ที่อยู่ที่แน่นอนของอ็อบเจ็กต์ที่อ้างอิงในหน่วยความจำ โปรดทราบว่าหลังจากเราเรียกใช้ Y = Y + X, id(Y) จะชี้ไปที่ตำแหน่งที่แตกต่างกัน นั่นเป็นเพราะ Python ประเมิน Y + X ก่อน จัดสรรหน่วยความจำใหม่สำหรับผลลัพธ์ แล้วจึงชี้ Y ไปที่ตำแหน่งใหม่นี้ในหน่วยความจำ

ตัวอย่างต่อไปนี้แสดงวิธีใช้ฟังก์ชัน id() เพื่อแสดงปัญหาการจัดสรรหน่วยความจำ:

In [ ]:
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# พิมพ์ id ของ Y
print(id(Y))

# บวก X และ Y
Y = Y + X

# พิมพ์ id ของ Y อีกครั้ง
print(id(Y))


132417111312976
132417111313072


โชคดีที่การทำ in-place operations นั้นง่ายมาก เราสามารถกำหนดผลลัพธ์ของการดำเนินการให้กับอาร์เรย์ Y ที่จัดสรรไว้ก่อนหน้านี้โดยใช้ slice notation: Y[:] = <expression>

เพื่ออธิบายแนวคิดนี้ เราได้เขียนทับค่าของเทนเซอร์ Z หลังจากทำการ 초기화โดยใช้ zeros_like เพื่อให้มีรูปร่างเดียวกันกับ Y

ตัวอย่างต่อไปนี้แสดงวิธีใช้ slice notation เพื่อทำ in-place operations:

In [ ]:
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# สร้างเทนเซอร์ Z
Z = np.zeros_like(Y)

# บวก X และ Y แบบ in-place
Y[:] = X + Y

# พิมพ์ค่าของ Y
print(Y)
#ตามที่คุณเห็น ค่าของ Y ได้ถูกเปลี่ยนเป็น [5, 7, 9] แบบ in-place โดยไม่จัดสรรหน่วยความจำใหม่



[5 7 9]


ตามที่คุณเห็น id ของ Y เปลี่ยนไปหลังจากที่เราเรียกใช้ Y = Y + X นั่นเป็นเพราะ Python ได้จัดสรรหน่วยความจำใหม่สำหรับผลลัพธ์

ปัญหานี้สามารถแก้ไขได้โดยใช้เทคนิคที่เรียกว่า "in-place operations" In-place operations ทำการคำนวณบนเทนเซอร์เดียวกันโดยหลีกเลี่ยงการจัดสรรหน่วยความจำใหม่ ตัวอย่างเช่น ใน PyTorch เราสามารถใช้ฟังก์ชัน add_() เพื่อบวก X และ Y แบบ in-place:

In [ ]:
import torch

# สร้างเทนเซอร์
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])
print(id(Y))
# บวก X และ Y แบบ in-place
Y.add_(X)

# พิมพ์ id ของ Y
print(id(Y))
print(Y)

132417111365472
132417111365472
tensor([5, 7, 9])


In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before


False

ตามที่คุณเห็น id ของ Y ไม่ได้เปลี่ยนไปหลังจากที่เราเรียกใช้ Y.add_(X) นั่นเป็นเพราะ PyTorch ได้ทำการคำนวณบนเทนเซอร์ Y เดิมโดยไม่จัดสรรหน่วยความจำใหม่

การใช้ in-place operations สามารถช่วยลดการใช้หน่วยความจำและปรับปรุงประสิทธิภาพของโปรแกรมของคุณ อย่างไรก็ตาม สิ่งสำคัญคือต้องใช้ in-place operations อย่างระมัดระวัง เพราะอาจนำไปสู่ผลลัพธ์ที่ไม่คาดคิดได้




ถ้าค่าของ X ไม่ได้ถูกนำมาใช้ซ้ำในคำนวณถัดไป เราก็สามารถใช้ X[:] = X + Y หรือ X += Y เพื่อลดค่าใช้จ่ายหน่วยความจำของการดำเนินการ

X[:] = X + Y เป็นการกำหนดผลลัพธ์ของ X + Y ให้กับเทนเซอร์ X แบบ in-place ในขณะที่ X += Y เป็นการกำหนดผลลัพธ์ของ X + Y ให้กับเทนเซอร์ X แบบ in-place เช่นกัน แต่ X += Y เป็นคำสั่งที่อ่านง่ายกว่า

In [ ]:
#ตัวอย่างต่อไปนี้แสดงวิธีใช้ X[:] = X + Y และ X += Y เพื่อทำ in-place
import numpy as np

# สร้างเทนเซอร์
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

before = id(X)
# บวก X และ Y แบบ in-place โดยใช้ X[:] = X + Y
X[:] = X + Y
print(id(X) == before)
# พิมพ์ค่าของ X
print(X)
id(X) == before
# บวก X และ Y แบบ in-place โดยใช้ X += Y
X += Y
print(id(X) == before)
# พิมพ์ค่าของ X อีกครั้ง
print(X)


True
[5 7 9]
True
[ 9 12 15]


## 2.1.6 Conversion to Other Python Objects


การแปลของข้อความที่คุณให้มานั้นเป็นดังนี้:

การแปลงเป็น NumPy tensor (ndarray) หรือ vice versa นั้นง่ายมาก เทนเซอร์ PyTorch และอาร์เรย์ NumPy จะแชร์หน่วยความจำพื้นฐานของตนเอง และการเปลี่ยนแปลงหนึ่งผ่านการดำเนินการ in-place จะเปลี่ยนแปลงอีกอันหนึ่งด้วยเช่นกัน

ตัวอย่างต่อไปนี้แสดงวิธีแปลงเทนเซอร์ PyTorch เป็นอาร์เรย์ NumPy และ vice versa:

In [ ]:
import torch
import numpy as np

# สร้างเทนเซอร์ PyTorch
x = torch.tensor([1, 2, 3])

# แปลงเทนเซอร์ PyTorch เป็นอาร์เรย์ NumPy
y = x.numpy()

# พิมพ์ค่าของ y
print(y)

# แปลงอาร์เรย์ NumPy เป็นเทนเซอร์ PyTorch
z = torch.from_numpy(y)

# พิมพ์ค่าของ z
print(z)
type(x),type(y),type(z)

[1 2 3]
tensor([1, 2, 3])


(torch.Tensor, numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)


(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.8 Exercises

1. รันโค้ดในส่วนนี้ เปลี่ยนเงื่อนไข X == Y เป็น X < Y หรือ X > Y แล้วดูว่าคุณจะได้เทนเซอร์แบบใด

In [ ]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([1, 2, 3])
Y = torch.tensor([2, 3, 4])

# สร้างเงื่อนไข X < Y หรือ X > Y
condition = X < Y

# พิมพ์ค่าของ condition
print(f"X < Y จะให้เทนเซอร์ต่อไปนี้:\n{condition}")


X < Y จะให้เทนเซอร์ต่อไปนี้:
tensor([True, True, True])


In [ ]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([1, 2, 3])
Y = torch.tensor([2, 3, 4])

# สร้างเงื่อนไข X < Y หรือ X > Y
condition = X > Y

# พิมพ์ค่าของ condition
print(f" X > Y จะให้เทนเซอร์ต่อไปนี้:\n{condition}")


 X > Y จะให้เทนเซอร์ต่อไปนี้:
tensor([False, False, False])


2. แทนที่เทนเซอร์ทั้งสองที่ดำเนินการแบบองค์ประกอบต่อองค์ประกอบในกลไกการกระจายเสียงด้วยรูปร่างอื่น เช่น เทนเซอร์สามมิติ ผลลัพธ์จะเหมือนกับที่คาดไว้หรือไม่

In [ ]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Y = torch.tensor([1, 2, 3])

# กระจายเสียงเทนเซอร์ Y เพื่อให้มีรูปร่างเดียวกันกับเทนเซอร์ X
Y_broadcast = Y.unsqueeze(0).unsqueeze(0).expand_as(X)

# บวกเทนเซอร์ X และ Y_broadcast แบบองค์ประกอบต่อองค์ประกอบ
Z = X + Y

# พิมพ์ค่าของ Z
print(Z)


tensor([[[ 2,  4,  6],
         [ 5,  7,  9]],

        [[ 8, 10, 12],
         [11, 13, 15]]])


In [ ]:
import torch

# สร้างเทนเซอร์ X และ Y
X = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Y = torch.tensor([1, 2, 3])

# กระจายเสียงเทนเซอร์ Y เพื่อให้มีรูปร่างเดียวกันกับเทนเซอร์ X
Y_broadcast = Y.unsqueeze(0).unsqueeze(0).expand_as(X)

# บวกเทนเซอร์ X และ Y_broadcast แบบองค์ประกอบต่อองค์ประกอบ
Z = X + Y_broadcast

# พิมพ์ค่าของ Z
print(Z)


tensor([[[ 2,  4,  6],
         [ 5,  7,  9]],

        [[ 8, 10, 12],
         [11, 13, 15]]])


ตามที่คุณเห็น เทนเซอร์ Z มีรูปร่างเดียวกันกับเทนเซอร์ X และค่าของแต่ละองค์ประกอบของ Z เป็นผลลัพธ์ของการบวกองค์ประกอบที่สอดคล้องกันของ X และ Y_broadcast

กลไกการกระจายเสียงเป็นเครื่องมือที่ทรงพลังที่ช่วยให้เราสามารถดำเนินการกับเทนเซอร์ที่มีรูปร่างต่างๆ ได้อย่างง่ายดาย โดยไม่ต้องใช้ลูป

# 2.2 Data Preprocessing

การแปลของข้อความที่คุณให้มานั้นเป็นดังนี้:

จนถึงตอนนี้ เราได้ทำงานกับข้อมูลสังเคราะห์ที่อยู่ในเทนเซอร์สำเร็จรูป อย่างไรก็ตาม ในการนำการเรียนรู้เชิงลึกไปใช้ในโลกแห่งความจริง เราต้องดึงข้อมูลที่สกปรกซึ่งเก็บอยู่ในรูปแบบต่างๆ และทำการประมวลผลก่อนล่วงหน้าเพื่อให้เหมาะสมกับความต้องการของเรา โชคดีที่ไลบรารี pandas สามารถช่วยยกของหนักๆ ให้เราได้ แม้ว่าส่วนนี้จะไม่ใช่การสอน pandas อย่างเหมาะสม แต่ก็จะให้บทเรียนเร่งรัดเกี่ยวกับฟังก์ชันการทำงานทั่วไปบางอย่าง

ไลบรารี pandas เป็นไลบรารี Python ที่ใช้สำหรับการวิเคราะห์และการจัดการข้อมูล มันมีโครงสร้างข้อมูลที่มีประสิทธิภาพสำหรับจัดเก็บและประมวลผลข้อมูลขนาดใหญ่ นอกจากนี้ยังมีเครื่องมือสำหรับการทำความสะอาดข้อมูล การรวมกลุ่ม และการแปลงข้อมูล

ฟังก์ชันการทำงานทั่วไปบางอย่างของ pandas ได้แก่:

* การอ่านและเขียนข้อมูลจาก/ไปยังไฟล์ต่างๆ เช่น CSV, Excel และ JSON
* การเลือกและกรองข้อมูล
* การรวมข้อมูลจากหลายแหล่ง
* การเติมเต็มค่าที่หายไป
* การแปลงประเภทข้อมูล
* การสร้างฟีเจอร์ใหม่

ในส่วนนี้ เราจะกล่าวถึงฟังก์ชันการทำงานบางอย่างของ pandas ที่มีประโยชน์สำหรับการประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก ตัวอย่างเช่น เราสามารถใช้ pandas เพื่อ:

* อ่านข้อมูลจากไฟล์ CSV และแปลงเป็นเทนเซอร์
* กรองข้อมูลที่ไม่สมบูรณ์หรือผิดปกติออก
* แปลงประเภทข้อมูลของคอลัมน์ต่างๆ ให้เหมาะสมกับการเรียนรู้เชิงลึก
* สร้างฟีเจอร์ใหม่จากข้อมูลที่มีอยู่

ต่อไปนี้เป็นตัวอย่างของการใช้ pandas เพื่อประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก:

```python
import pandas as pd

# อ่านข้อมูลจากไฟล์ CSV
df = pd.read_csv('data.csv')

# กรองข้อมูลที่ไม่สมบูรณ์หรือผิดปกติออก
df = df.dropna()
df = df[df['price'] > 0]

# แปลงประเภทข้อมูลของคอลัมน์ต่างๆ ให้เหมาะสมกับการเรียนรู้เชิงลึก
df['price'] = pd.to_numeric(df['price'])
df['category'] = pd.get_dummies(df['category'])

# สร้างฟีเจอร์ใหม่จากข้อมูลที่มีอยู่
df['feature_1'] = df['price'] * df['quantity']

# แปลงข้อมูลเป็นเทนเซอร์
X = df[['feature_1', 'category']].to_numpy()
y = df['price'].to_numpy()
```

ข้อมูลในเทนเซอร์ X และ y พร้อมสำหรับการใช้ในโมเดลการเรียนรู้เชิงลึกแล้ว

ไลบรารี pandas เป็นเครื่องมือที่ทรงพลังสำหรับการประมวลผลข้อมูลก่อนล่วงหน้าสำหรับการเรียนรู้เชิงลึก หากคุณกำลังทำงานกับข้อมูลจริง ขอแนะนำให้คุณศึกษาเกี่ยวกับ pandas เพิ่มเติม

In [ ]:
import os

# เชื่อมต่อ Google Drive กับ Google Colab


# เก็บไฟล์ house_tiny.csv ไว้ที่ตัวแปร data_file
data_file = '/content/drive/My Drive/house_tiny.csv'


In [ ]:
import os

# สร้างไดเร็กทอรี data ถ้ายังไม่มีอยู่
os.makedirs(os.path.join('..', 'data'), exist_ok=True)

# สร้างไฟล์ house_tiny.csv ในไดเร็กทอรี data
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# เขียนข้อมูลไปยังไฟล์ house_tiny.csv
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [ ]:
data.isnull().sum()

NumRooms    2
RoofType    3
Price       0
dtype: int64

In [ ]:
data.shape

(4, 3)

In [ ]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)


   NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1


In [ ]:
c = inputs.fillna(inputs.mean())
print(inputs)
type(X)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1


torch.Tensor

## 2.2.3 Conversion to the Tensor Format


In [ ]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X,y

(tensor([[nan, 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [nan, 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [ ]:
type(X),type(y)

(torch.Tensor, torch.Tensor)

2.2.4 Discussion

ขณะนี้คุณทราบวิธีการแบ่งพาร์ติชันคอลัมน์ข้อมูล อุดรูรั่วของตัวแปร และโหลดข้อมูลแพนด้าลงในเทนเซอร์แล้ว ในส่วน 5.7 คุณจะได้เรียนรู้ทักษะการประมวลผลข้อมูลเพิ่มเติม

แม้ว่าหลักสูตรเร่งรัดนี้จะทำให้ทุกอย่างเรียบง่าย แต่การประมวลผลข้อมูลอาจเป็นเรื่องที่ยุ่งยาก เช่น แทนที่จะมาถึงในไฟล์ CSV เดียว ชุดข้อมูลของเราอาจกระจายอยู่ทั่วหลายไฟล์ที่แยกจากฐานข้อมูลเชิงสัมพันธ์ ตัวอย่างเช่น ในแอพพลิเคชันอีคอมเมิร์ซ ที่อยู่ของลูกค้าอาจอยู่ในตารางหนึ่งและข้อมูลการซื้อขายอยู่ในตารางอื่น นอกจากนี้ ผู้ปฏิบัติงานยังต้องเผชิญกับประเภทข้อมูลนับไม่ถ้วนเกินกว่าประเภทข้อมูลประเภทและตัวเลข เช่น สตริงข้อความ รูปภาพ ข้อมูลเสียง และกลุ่มจุด บ่อยครั้ง ต้องใช้เครื่องมือขั้นสูงและอัลกอริธึมที่มีประสิทธิภาพเพื่อป้องกันไม่ให้การประมวลผลข้อมูลกลายเป็นอุปสรรคที่ใหญ่ที่สุดในกระบวนการเรียนรู้ของเครื่อง ปัญหาเหล่านี้จะเกิดขึ้นเมื่อเราเข้าสู่การประมวลผลภาพคอมพิวเตอร์และการประมวลผลภาษาธรรมชาติ ในที่สุด เราต้องใส่ใจกับคุณภาพของข้อมูล ชุดข้อมูลในโลกแห่งความจริงมักเต็มไปด้วยค่าผิดปกติ การวัดที่ผิดพลาดจากเซ็นเซอร์ และข้อผิดพลาดในการบันทึก ซึ่งต้องได้รับการแก้ไขก่อนป้อนข้อมูลเข้าสู่อะไรๆ โมเดล เครื่องมือการแสดงข้อมูล เช่น seaborn47 Bokeh48 หรือ matplotlib49 สามารถช่วยคุณตรวจสอบข้อมูลด้วยตนเองและพัฒนาสัญชาตญาณเกี่ยวกับประเภทของปัญหาที่คุณอาจต้องแก้ไข

## 2.2.5 Exercises

ลองโหลดชุดข้อมูล เช่น Abalone จาก UCI Machine Learning Repository50 และตรวจสอบคุณสมบัติของชุดข้อมูล มีกี่เปอร์เซ็นต์ของชุดข้อมูลที่มีค่าที่ขาดหายไป มีกี่เปอร์เซ็นต์ของตัวแปรที่เป็นตัวเลข ประเภท หรือข้อความ

In [ ]:
!pip install ucimlrepo

In [ ]:
import pandas as pd

from ucimlrepo import fetch_ucirepo

# fetch dataset
adult = fetch_ucirepo(id=2)

# data (as pandas dataframes)
X = adult.data.features
y = adult.data.targets

# metadata
print(adult.metadata)

# variable information
print(adult.variables)

# convert data to DataFrames
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# save DataFrames to CSV files
X.to_csv("adult_X.csv")
y.to_csv("adult_y.csv")


{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether income exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Mon Aug 07 2023', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': 'Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAG

In [ ]:
X.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country  
0          2174             0              40  United-States  
1             0             0              13  United-States  
2             0             0              40  United-States  
3             0             0              40  United-States  
4             0             0              40           Cuba

In [ ]:
X.isnull().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

2. ลองทำการจัดทำดัชนีและเลือกคอลัมน์ข้อมูลตามชื่อแทนที่จะเป็นหมายเลขคอลัมน์ เอกสารประกอบของ pandas เกี่ยวกับการจัดทำดัชนี51 มีรายละเอียดเพิ่มเติมเกี่ยวกับวิธีการทำสิ่งนี้

In [ ]:
data = pd.concat([X, y], axis=1)
data.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [ ]:
selected_columns = data.loc[:, ["workclass", "age"]]
selected_columns.sum()

<ipython-input-63-5025e6de8da4>:2: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  selected_columns.sum()


age    1887430
dtype: int64

#2.3 Linear Algebra



ขณะนี้เราสามารถโหลดชุดข้อมูลลงในเทนเซอร์และจัดการเทนเซอร์เหล่านี้ด้วยการดำเนินการทางคณิตศาสตร์พื้นฐานได้แล้ว ในการเริ่มสร้างโมเดลที่ซับซ้อนขึ้น เราจะต้องใช้เครื่องมือจากพีชคณิตเชิงเส้นด้วย ส่วนนี้จะนำเสนอแนวคิดที่สำคัญที่สุดอย่างราบรื่น โดยเริ่มจากการคำนวณเลขคณิตสเกลาร์และเพิ่มระดับความยากขึ้นไปจนถึงการคูณเมทริกซ์

พีชคณิตเชิงเส้นเป็นสาขาหนึ่งของคณิตศาสตร์ที่เกี่ยวข้องกับเวกเตอร์ เมทริกซ์ และการแปลงเชิงเส้น พีชคณิตเชิงเส้นใช้ในหลายสาขาวิชา รวมถึงฟิสิกส์ วิศวกรรมศาสตร์ และวิทยาการคอมพิวเตอร์

ในวิทยาการคอมพิวเตอร์ พีชคณิตเชิงเส้นใช้ในหลายงาน รวมถึงการประมวลผลภาพ การประมวลผลภาษาธรรมชาติ และการเรียนรู้ของเครื่อง

ส่วนนี้จะแนะนำแนวคิดที่สำคัญที่สุดในพีชคณิตเชิงเส้นอย่างราบรื่น โดยเริ่มจากการคำนวณเลขคณิตสเกลาร์และเพิ่มระดับความยากขึ้นไปจนถึงการคูณเมทริกซ์ ความรู้เหล่านี้จะจำเป็นสำหรับการสร้างโมเดลการเรียนรู้ของเครื่องที่ซับซ้อนขึ้น

ต่อไปนี้คือคำอธิบายสั้นๆ ของหัวข้อที่กล่าวถึงในส่วนนี้:

* เลขคณิตสเกลาร์: เลขคณิตสเกลาร์คือการดำเนินการทางคณิตศาสตร์กับตัวเลข เช่น การบวก ลบ การคูณ และการหาร
* เวกเตอร์: เวกเตอร์คือลำดับของตัวเลขที่มีทิศทางและขนาด เวกเตอร์ใช้ในการแสดงข้อมูลที่มีทิศทางและขนาด เช่น ความเร็วและแรง
* เมทริกซ์: เมทริกซ์คือตารางของตัวเลข เมทริกซ์ใช้ในการแสดงข้อมูลที่มีหลายมิติ เช่น รูปภาพและวิดีโอ
* การแปลงเชิงเส้น: การแปลงเชิงเส้นคือการดำเนินการที่ใช้เวกเตอร์เพื่อสร้างเวกเตอร์อื่น การแปลงเชิงเส้นใช้ในการเปลี่ยนแปลงข้อมูล เช่น การหมุนและการย่อขนาด

หากคุณต้องการเรียนรู้เพิ่มเติมเกี่ยวกับพีชคณิตเชิงเส้น มีทรัพยากรมากมายให้บริการออนไลน์และในห้องสมุด

In [ ]:
import torch

## 2.3.1 Scalars



คณิตศาสตร์ในชีวิตประจำวันส่วนใหญ่ประกอบด้วยการจัดการตัวเลขหนึ่งตัวในแต่ละครั้ง โดยทางการ เราเรียกค่าเหล่านี้ว่าค่าสเกลาร์ ตัวอย่างเช่น อุณหภูมิใน Palo Alto อยู่ที่ 72 องศาฟาเรนไฮต์ หากคุณต้องการแปลงอุณหภูมิเป็นเซลเซียส คุณจะประเมินนิพจน์ $c = \frac{5}{9}(f-32)$ โดยตั้งค่า $f$ เป็น 72 ในสมการนี้ ค่า 5, 9 และ 32 คือค่าสเกลาร์คงที่ ตัวแปร $c$ และ $f$ โดยทั่วไปแทนค่าสเกลาร์ที่ไม่รู้จัก เราแสดงสเกลาร์ด้วยตัวอักษรพิมพ์เล็กธรรมดา (เช่น $x$, $y$ และ $z$) และใช้สัญลักษณ์ $R$ แทนสเปซของสเกลาร์ค่าจริงทั้งหมด (ต่อเนื่อง) เพื่อความรวดเร็ว เราจะข้ามนิยามที่เข้มงวดของสเปซ: เพียงจำไว้ว่านิพจน์ $x \in R$ เป็นวิธีการพูดอย่างเป็นทางการว่า $x$ คือสเกลาร์ค่าจริง สัญลักษณ์ $\in$ (ออกเสียงว่า "ใน") หมายถึงการเป็นสมาชิกของเซต ตัวอย่างเช่น $x, y \in \{0, 1\}$ หมายความว่า $x$ และ $y$ คือตัวแปรที่สามารถรับค่าได้เพียง 0 หรือ 1 เท่านั้น

สเกลาร์ถูกนำมาใช้เป็นเทนเซอร์ที่มีองค์ประกอบเพียงหนึ่งองค์ประกอบ ด้านล่าง เรากำหนดสเกลาร์สองตัวและดำเนินการบวก คูณ หาร และยกกำลังที่คุ้นเคย

ตัวอย่าง:

```python
import torch

# define two scalars
a = torch.tensor(5)
b = torch.tensor(2)

# perform addition, multiplication, division, and exponentiation
print(a + b)
print(a * b)
print(a / b)
print(a ** b)
```

ผลลัพธ์:

```
tensor(7)
tensor(10)
tensor(2.5000)
tensor(25)
```

เราจะใช้สเกลาร์ในหลายส่วนของหนังสือเล่มนี้ ตัวอย่างเช่น เราจะใช้สเกลาร์เพื่อแสดงอัตราการเรียนรู้ของโมเดลการเรียนรู้ของเครื่องหรือเพื่อแสดงความสำคัญของฟีเจอร์ในชุดข้อมูล

In [ ]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

##2.3.2 Vectors


สำหรับวัตถุประสงค์ในปัจจุบัน คุณสามารถคิดถึงเวกเตอร์เป็นอาร์เรย์ของสเกลาร์ความยาวคงที่ เช่นเดียวกับคำสั่งของโค้ด เราเรียกสเกลาร์เหล่านี้ว่าองค์ประกอบของเวกเตอร์ (คำพ้องความหมายรวมถึงรายการและส่วนประกอบ) เมื่อเวกเตอร์แสดงถึงตัวอย่างจากชุดข้อมูลในโลกจริง ค่าของเวกเตอร์จะมีความสำคัญในโลกจริง ตัวอย่างเช่น หากเรากำลังฝึกโมเดลเพื่อทำนายความเสี่ยงของการผิดนัดชำระเงินกู้ เราอาจเชื่อมโยงผู้สมัครแต่ละรายกับเวกเตอร์ที่มีองค์ประกอบสอดคล้องกับปริมาณเช่นรายได้ ระยะเวลาการทำงาน หรือจำนวนการผิดนัดชำระเงินก่อนหน้านี้ หากเรากำลังศึกษาความเสี่ยงของโรคหัวใจ วนตรอัคคี แต่ละเวกเตอร์อาจแสดงถึงผู้ป่วยและองค์ประกอบของเวกเตอร์อาจสอดคล้องกับสัญญาณชีพล่าสุด ระดับคอเลสเตอรอล จำนวนนาทีของการออกกำลังกายต่อวัน ฯลฯ เราแสดงเวกเตอร์ด้วยตัวอักษรพิมพ์เล็กตัวหนา (เช่น $\mathbf{x}$, $\mathbf{y}$ และ $\mathbf{z}$)

เวกเตอร์ถูกนำมาใช้เป็นเทนเซอร์ลำดับที่ 1 โดยทั่วไป เทนเซอร์ดังกล่าวสามารถมีความยาวได้ตามต้องการ ขึ้นอยู่กับข้อจำกัดของหน่วยความจำ อย่างไรก็ตาม โปรดทราบว่าใน Python เช่นเดียวกับในภาษาโปรแกรมส่วนใหญ่ ดัชนีเวกเตอร์เริ่มต้นที่ 0 ซึ่งเรียกว่าการจัดทำดัชนีแบบ zero-based ในขณะที่ในพีชคณิตเชิงเส้น ดัชนีเริ่มต้นที่ 1 (การจัดทำดัชนีแบบ one-based)

ตัวอย่าง:

```python
import torch

# define a vector
x = torch.tensor([1, 2, 3])

# print the elements of the vector
print(x)

# print the length of the vector
print(x.numel())
```

ผลลัพธ์:

```
tensor([1, 2, 3])
3
```

เราจะใช้เวกเตอร์ในหลายส่วนของหนังสือเล่มนี้ ตัวอย่างเช่น เราจะใช้เวกเตอร์เพื่อแสดงอินพุตและเอาต์พุตของโมเดลการเรียนรู้ของเครื่อง หรือเพื่อแสดงการแทนค่าของภาพหรือวิดีโอ

In [ ]:
x = torch.arange(3,dtype = float)
x

tensor([0., 1., 2.], dtype=torch.float64)



เวกเตอร์สามารถแสดงเป็นอาร์เรย์ของสเกลาร์ที่มีความยาวคงที่ ตัวอย่างเช่น หากเรากำลังสร้างโมเดลเพื่อทำนายความเสี่ยงของการผิดนัดชำระเงินกู้ เราอาจแสดงแต่ละผู้สมัครโดยใช้เวกเตอร์ที่มีองค์ประกอบสอดคล้องกับปริมาณเช่นรายได้ ระยะเวลาการทำงาน หรือจำนวนการผิดนัดชำระเงินก่อนหน้านี้ ในกรณีนี้ องค์ประกอบของเวกเตอร์จะแสดงถึงข้อมูลที่มีความสำคัญในโลกจริง

เวกเตอร์แสดงโดยตัวอักษรพิมพ์เล็กตัวหนา (เช่น $\mathbf{x}$, $\mathbf{y}$ และ $\mathbf{z}$) ในภาษาไพธอน ดัชนีเวกเตอร์เริ่มต้นที่ 0 ซึ่งเรียกว่าการจัดทำดัชนีแบบ zero-based ในขณะที่ในพีชคณิตเชิงเส้น ดัชนีเริ่มต้นที่ 1 (การจัดทำดัชนีแบบ one-based)

เราสามารถอ้างอิงองค์ประกอบของเวกเตอร์โดยใช้ดัชนี ตัวอย่างเช่น $\mathbf{x}_2$ หมายถึงองค์ประกอบที่สองของ $\mathbf{x}$ เนื่องจาก $\mathbf{x}_2$ เป็นสเกลาร์ เราจึงไม่ใช้ตัวหนา

โดยทั่วไป เราจะแสดงเวกเตอร์โดยเรียงองค์ประกอบตามแนวตั้ง ตัวอย่างเช่น

$\mathbf{x} = \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}$


ในภายหลัง เราจะแยกความแตกต่างระหว่างเวกเตอร์คอลัมน์ดังกล่าวกับเวกเตอร์แถวที่มีองค์ประกอบเรียงตามแนวนอน

เราสามารถเข้าถึงองค์ประกอบของเทนเซอร์ได้ผ่านการจัดทำดัชนี ตัวอย่างเช่น ใน Python เราสามารถเข้าถึงองค์ประกอบที่สองของเวกเตอร์ $\mathbf{x}$ ได้โดยใช้โค้ดต่อไปนี้:

```python
import torch

x = torch.tensor([1, 2, 3])

# print the second element of x
print(x[1])
```

ผลลัพธ์:

```
2
```

In [ ]:
len(x)

3

In [ ]:
x.shape

torch.Size([3])


บางครั้งคำว่า "มิติ" มักใช้แทนความหมายทั้งจำนวนแกน และความยาวตามแกนใดแกนหนึ่ง เพื่อหลีกเลี่ยงความสับสน เราจะใช้คำว่า "ลำดับ" แทนจำนวนแกน และคำว่า "มิติ" แทนจำนวนองค์ประกอบ

ตัวอย่างเช่น เวกเตอร์หนึ่งมิติ (1D) หมายถึงเวกเตอร์ที่มีองค์ประกอบเดียว เวกเตอร์สองมิติ (2D) หมายถึงเวกเตอร์ที่มีองค์ประกอบสององค์ประกอบ เรียงตามแนวแกน X และ Y ตามลำดับ เวกเตอร์สามมิติ (3D) หมายถึงเวกเตอร์ที่มีองค์ประกอบสามองค์ประกอบ เรียงตามแนวแกน X, Y และ Z ตามลำดับ

ในรูปภาพต่อไปนี้ แสดงตัวอย่างเวกเตอร์สามมิติ (3D)

```
x
y
z
```

เวกเตอร์นี้ประกอบด้วยสามองค์ประกอบ แต่ละองค์ประกอบแสดงถึงตำแหน่งของจุดในอวกาศสามมิติ องค์ประกอบแรก (x) แสดงถึงตำแหน่งของจุดตามแนวแกน X องค์ประกอบที่สอง (y) แสดงถึงตำแหน่งของจุดตามแนวแกน Y และองค์ประกอบที่สาม (z) แสดงถึงตำแหน่งของจุดตามแนวแกน Z

การใช้คำว่า "ลำดับ" และ "มิติ" แทนความหมายที่ต่างกันจะช่วยให้เราสื่อสารได้อย่างถูกต้องและเข้าใจง่ายขึ้น

2.3.3 Matrices




เมทริกซ์เป็นเทนเซอร์ลำดับที่สอง เช่นเดียวกับสเกลาร์ที่เป็นเทนเซอร์ลำดับที่ 0 และเวกเตอร์ที่เป็นเทนเซอร์ลำดับที่ 1 เราแสดงเมทริกซ์ด้วยตัวอักษรพิมพ์ใหญ่ตัวหนา (เช่น $X$, $Y$ และ $Z$) และแสดงในโค้ดโดยเทนเซอร์ที่มีสองแกน นิพจน์ $A \in R^{m\times n}$ แสดงว่าเมทริกซ์ $A$ มีสเกลาร์ค่าจริง $m \times n$ เรียงเป็น $m$ แถวและ $n$ คอลัมน์ เมื่อ $m = n$ เราจะบอกว่าเมทริกซ์เป็นเมทริกซ์จัตุรัส เราสามารถแสดงเมทริกซ์ใด ๆ ในรูปแบบตารางได้ ในการอ้างอิงองค์ประกอบแต่ละองค์ประกอบ เราจะใส่ดัชนีแถวและคอลัมน์เป็นตัวห้อย ตัวอย่างเช่น $a_{ij}$ คือค่าที่อยู่ในแถวที่ $i$ และคอลัมน์ที่ $j$ ของ $A$ =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots  & \vdots  & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}


ในโค้ด เราแสดงเมทริกซ์ $A \in R^{m\times n}$ ด้วยเทนเซอร์ลำดับที่สองที่มีรูปร่าง $(m, n)$ เราสามารถแปลงเทนเซอร์ $m \times n$ ที่มีขนาดเหมาะสมเป็นเมทริกซ์ $m \times n$ ได้โดยส่งผ่านรูปร่างที่ต้องการไปยัง reshape

ตัวอย่าง:

```python
import torch

# define a 2D tensor
x = torch.tensor([[1, 2], [3, 4]])

# print the shape of the tensor
print(x.shape)

# convert the tensor to a 2x2 matrix
y = x.reshape((2, 2))

# print the matrix
print(y)
```

ผลลัพธ์:

```
torch.Size([2, 2])
tensor([[1, 2],
       [3, 4]])
```

เมทริกซ์ใช้ในหลายงานการประมวลผลข้อมูล เช่น การคูณเมทริกซ์ การผกผันเมทริกซ์ และการแก้สมการเชิงเส้น

หรือ


In [ ]:
A = torch.arange(6,dtype=int).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

การแปลและเรียบเรียงอ่านเรียนรู้ง่ายของประโยค "B = A>, then 𝑏𝑖 𝑗 = 𝑎 𝑗𝑖 for all 𝑖 and 𝑗. Thus, the transpose of an 𝑚 × 𝑛 matrix is an 𝑛 × 𝑚
matrix:
A> =

In code, we can access any matrix’s transpose as follows:" มีดังนี้:

"เมทริกซ์ผกผัน (transpose) ของเมทริกซ์ $A$ นั้น จะได้โดยการสลับตำแหน่งของแถวและคอลัมน์


$$
\mathbf{A}^\top =
\begin{bmatrix}
    a_{11} & a_{21} & \dots  & a_{m1} \\
    a_{12} & a_{22} & \dots  & a_{m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    a_{1n} & a_{2n} & \dots  & a_{mn}
\end{bmatrix}.
$$


ในโค้ด เราสามารถเข้าถึงเมทริกซ์ผกผันของเมทริกซ์ใด ๆ ได้โดยการใช้ฟังก์ชัน `transpose()` ดังนี้"

ตัวอย่าง:

```python
import torch

# define a 2x2 matrix
A = torch.tensor([[1, 2], [3, 4]])

# print the transpose of A
print(A.transpose(1, 0))
```

ผลลัพธ์:

```
tensor([[1, 3],
       [2, 4]])
```

การแปลและเรียบเรียงประโยคนี้เป็นภาษาง่าย ๆ ดังนี้:

"เมทริกซ์ผกผันคือเมทริกซ์ที่แถวและคอลัมน์สลับตำแหน่งกัน ตัวอย่างเช่น เมทริกซ์ $A$ ต่อไปนี้

```
A =

[1 2]
[3 4]
```

เมทริกซ์ผกผันของเมทริกซ์ $A$ คือ

```
A> =

[1 3]
[2 4]
```

ในโค้ด เราสามารถใช้ฟังก์ชัน `transpose()` เพื่อหาเมทริกซ์ผกผันของเมทริกซ์ใด ๆ ได้โดยการเปลี่ยนตำแหน่งของแถวและคอลัมน์"

หวังว่าจะช่วยให้เข้าใจได้ง่ายขึ้นนะคะ

In [ ]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
A.T #A transpose

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are the subset of square matrices that are equal to their own transposes:
A = A>. The following matrix is symmetric:

In [ ]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])



"เมทริกซ์เป็นเครื่องมือที่มีประโยชน์ในการแทนข้อมูลชุดข้อมูล โดยปกติแล้ว แถวของเมทริกซ์จะแทนข้อมูลแต่ละรายการ และคอลัมน์ของเมทริกซ์จะแทนคุณสมบัติที่แตกต่างกันของข้อมูลแต่ละรายการ"

การแปลประโยคนี้เป็นภาษาง่าย ๆ ดังนี้:

"เมทริกซ์สามารถใช้ในการแสดงข้อมูลชุดข้อมูล โดยแถวของเมทริกซ์จะแทนข้อมูลแต่ละรายการ เช่น ข้อมูลลูกค้า หรือข้อมูลสินค้า และคอลัมน์ของเมทริกซ์จะแทนคุณสมบัติที่แตกต่างกันของข้อมูลแต่ละรายการ เช่น ชื่อ ที่อยู่ หรือราคา"

ตัวอย่างเช่น เมทริกซ์ที่แสดงข้อมูลลูกค้าอาจมีลักษณะดังนี้:


| ชื่อ | ที่อยู่ | เบอร์โทรศัพท์ |
|---|---|---|
| นาย ก | บ้านเลขที่ 123 ถนนสุขุมวิท แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10320 | 081-234-5678 |
| นาง ข | บ้านเลขที่ 456 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400 | 092-345-6789 |


ในเมทริกซ์นี้ แถวที่ 1 แทนข้อมูลลูกค้ารายแรก แถวที่ 2 แทนข้อมูลลูกค้ารายที่สอง และคอลัมน์แรกแทนชื่อ คอลัมน์ที่สองแทนที่อยู่ และคอลัมน์ที่สามแทนเบอร์โทรศัพท์

การแทนข้อมูลชุดข้อมูลด้วยเมทริกซ์มีประโยชน์หลายประการ ตัวอย่างเช่น ทำให้สามารถจัดระเบียบข้อมูลได้ง่ายขึ้น ทำให้สามารถเปรียบเทียบข้อมูลชุดข้อมูลที่แตกต่างกันได้ง่ายขึ้น และทำให้สามารถวิเคราะห์ข้อมูลชุดข้อมูลได้ง่ายขึ้น

##2.3.4 Tensors:



 เทนเซอร์

แม้ว่าคุณจะสามารถไปได้ไกลในการเดินทางด้านการเรียนรู้ของเครื่องด้วยสเกลาร์ เวกเตอร์ และเมทริกซ์เท่านั้น แต่ในที่สุดคุณอาจต้องทำงานกับเทนเซอร์ลำดับที่สูงกว่า เทนเซอร์เป็นวิธีการทั่วไปในการอธิบายส่วนขยายของอาร์เรย์ลำดับที่ n เทนเซอร์ยังเป็นชื่อของวัตถุซอฟต์แวร์ของคลาสเทนเซอร์ เนื่องจากเทนเซอร์เหล่านี้สามารถมีแกนได้ตามจำนวนที่ต้องการ ในขณะที่อาจสับสนที่จะใช้คำว่าเทนเซอร์สำหรับทั้งวัตถุทางคณิตศาสตร์และการนำเสนอในโค้ด แต่ความหมายของเราโดยปกติจะชัดเจนจากบริบท เราแสดงเทนเซอร์ทั่วไปด้วยตัวพิมพ์ใหญ่ที่มีรูปแบบฟอนต์พิเศษ (เช่น $\mathsf{X}$, $\mathsf{Y}$ และ $\mathsf{Z}$) และกลไกการจัดทำดัชนีของเทนเซอร์ (เช่น $x_{ijk}$ และ $[\mathsf{X}]_{1, 2i-1, 3}$) จะตามมาอย่างเป็นธรรมชาติจากกลไกการจัดทำดัชนีของเมทริกซ์

เทนเซอร์จะกลายเป็นสิ่งสำคัญมากขึ้นเมื่อเราเริ่มทำงานกับรูปภาพ แต่ละภาพจะมาถึงในรูปแบบเทนเซอร์ลำดับที่ 3 ที่มีแกนสอดคล้องกับความสูง ความกว้าง และช่องสัญญาณ ที่ตำแหน่งเชิงพื้นที่แต่ละตำแหน่ง ความเข้มของแต่ละสี (แดง เขียว และน้ำเงิน) จะถูกจัดเรียงตามช่องสัญญาณ นอกจากนี้ ชุดรูปภาพจะถูกแสดงในโค้ดโดยเทนเซอร์ลำดับที่ 4 โดยรูปภาพที่แตกต่างกันจะถูกจัดทำดัชนีตามแกนแรก เทนเซอร์ลำดับที่สูงกว่าจะถูกสร้างขึ้นเช่นเดียวกับเวกเตอร์และเมทริกซ์ โดยการเพิ่มจำนวนส่วนประกอบรูปร่าง

สรุป:

เทนเซอร์เป็นวัตถุทางคณิตศาสตร์ที่สามารถใช้ในการแทนข้อมูลที่มีหลายมิติ เช่น รูปภาพและวิดีโอ เทนเซอร์สามารถมีแกนได้ตามจำนวนที่ต้องการ ซึ่งหมายความว่าสามารถใช้ในการแทนข้อมูลที่ซับซ้อนได้

เทนเซอร์จะกลายเป็นสิ่งสำคัญมากขึ้นเมื่อเราเริ่มทำงานกับรูปภาพ แต่ละภาพสามารถแสดงเป็นเทนเซอร์ลำดับที่ 3 ได้ โดยมีแกนสอดคล้องกับความสูง ความกว้าง และช่องสัญญาณ ช่องสัญญาณคือข้อมูลที่แสดงถึงสีของพิกเซล

ชุดรูปภาพสามารถแสดงเป็นเทนเซอร์ลำดับที่ 4 ได้ โดยมีแกนแรกแสดงถึงรูปภาพแต่ละรูป และแกนที่เหลือแสดงถึงความสูง ความกว้าง และช่องสัญญาณของรูปภาพ

เทนเซอร์ลำดับที่สูงกว่าสามารถใช้ในการแทนข้อมูลที่มีหลายมิติมากขึ้น เช่น วิดีโอและข้อมูลเซ็นเซอร์

In [ ]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5 Basic Properties of Tensor Arithmetic




สเกลาร์ เวกเตอร์ เมทริกซ์ และเทนเซอร์ลำดับที่สูงกว่า ล้วนมีคุณสมบัติที่มีประโยชน์บางอย่าง เช่น การดำเนินการแบบองค์ประกอบจะสร้างเอาต์พุตที่มีรูปร่างเหมือนกันกับอินพุต




In [ ]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() # Assign a copy of A to B by allocating new memory
A, A + B


(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))




"ผลคูณแบบองค์ประกอบของเมทริกซ์สองตัว เรียกว่า ผลคูณแบบ Hadamard (แสดงโดย ⊙ เราสามารถเขียนองค์ประกอบของผลคูณแบบ Hadamard ของเมทริกซ์สองตัว $\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times n}$:



$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.
$$

โดยที่ a
ij
​
  และ b
ij
​
  คือองค์ประกอบที่แถวที่ i และคอลัมน์ที่ j ของเมทริกซ์ A และ B ตามลำดับ

In [ ]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

การแปลและเรียบเรียงอ่านเรียนรู้ง่ายของประโยค "[Adding or multiplying a scalar and a tensor] produces a result with the same shape as the original tensor. Here, each element of the tensor is added to (or multiplied by) the scalar." มีดังนี้:

"การบวกหรือคูณสเกลาร์และเทนเซอร์ จะได้ผลลัพธ์ที่มีรูปร่างเหมือนกับเทนเซอร์เดิม โดยแต่ละองค์ประกอบของเทนเซอร์จะถูกบวก (หรือคูณ) ด้วยสเกลาร์"

ตัวอย่างเช่น หากเรามีเทนเซอร์ $A$ ที่มีรูปร่าง $(2,3)$ และสเกลาร์ $b$, เราสามารถบวกหรือคูณ $A$ และ $b$ ได้ดังนี้:

```
A = [[1, 2, 3], [4, 5, 6]]
b = 5

# การบวกสเกลาร์และเทนเซอร์
C = A + b

# การคูณสเกลาร์และเทนเซอร์
D = A * b

# ผลลัพธ์
C = [[6, 7, 8], [9, 10, 11]]
D = [[5, 10, 15], [20, 25, 30]]
```

การบวกและการคูณสเกลาร์และเทนเซอร์เป็นการดำเนินการพื้นฐานในการประมวลผลข้อมูล สามารถใช้ในการรวมข้อมูลจากหลายแหล่งเข้าด้วยกัน การเปลี่ยนแปลงรูปร่างของข้อมูล และการคำนวณที่ซับซ้อนอื่นๆ ได้

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

2.3.6 Reduction


การแปลของประโยค "Often, we wish to calculate the sum of a tensor’s elements. To express the sum of the
elements in a vector x of length 𝑛, we write Í𝑛
𝑖=1
𝑥𝑖
. There is a simple function for it:" คือ

"บ่อยครั้งที่เราต้องการคำนวณผลรวมขององค์ประกอบของเทนเซอร์ เพื่อแสดงผลรวมขององค์ประกอบในเวกเตอร์ $x$ ที่มีความยาว $n$ เราเขียนว่า $\sum_{i=1}^{n} x_i$ มีฟังก์ชันง่ายๆ สำหรับสิ่งนี้คือ"

ฟังก์ชันที่ง่ายที่สุดสำหรับคำนวณผลรวมขององค์ประกอบของเทนเซอร์คือฟังก์ชัน `sum()` ใน PyTorch ฟังก์ชันนี้สามารถใช้คำนวณผลรวมขององค์ประกอบของเทนเซอร์ที่มีแกนใดก็ได้ ตัวอย่างเช่น หากเรามีเทนเซอร์ $A$ ที่มีรูปร่าง $(2,3)$, เราสามารถคำนวณผลรวมขององค์ประกอบทั้งหมดของเทนเซอร์ได้ดังนี้:

```python
import torch

A = torch.tensor([[1, 2, 3], [4, 5, 6]])

# คำนวณผลรวมขององค์ประกอบทั้งหมดของเทนเซอร์
sum_of_all_elements = A.sum()

# พิมพ์ผลลัพธ์
print(sum_of_all_elements)
```

ผลลัพธ์:

```
21.0
```

เรายังสามารถใช้ฟังก์ชัน `sum()` เพื่อคำนวณผลรวมขององค์ประกอบของเทนเซอร์ตามแกนที่เฉพาะเจาะจง ตัวอย่างเช่น หากเราต้องการคำนวณผลรวมขององค์ประกอบของแต่ละแถวของเทนเซอร์ $A$ เราสามารถใช้ฟังก์ชัน `sum()` ได้ดังนี้:

```python
# คำนวณผลรวมขององค์ประกอบของแต่ละแถวของเทนเซอร์
sum_of_rows = A.sum(dim=1)

# พิมพ์ผลลัพธ์
print(sum_of_rows)
```

ผลลัพธ์:

```
tensor([6., 15.])
```

ฟังก์ชัน `sum()` เป็นฟังก์ชันที่มีประโยชน์ในการประมวลผลข้อมูล สามารถใช้คำนวณผลรวมขององค์ประกอบของเทนเซอร์ที่มีขนาดและรูปร่างใดก็ได้

In [ ]:
import torch

A = torch.arange(30).reshape(5,3,2)
print(A)
# คำนวณผลรวมขององค์ประกอบทั้งหมดของเทนเซอร์
sum_of_all_elements = A.sum()

# พิมพ์ผลลัพธ์
print(sum_of_all_elements)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]]])
tensor(435)




เพื่อแสดงผลรวมขององค์ประกอบของเทนเซอร์ที่มีรูปร่างใดก็ได้ เราเพียงแค่บวกเหนือแกนทั้งหมดของเทนเซอร์ ตัวอย่างเช่น ผลรวมขององค์ประกอบของเมทริกซ์ $m \times n$ $\mathbf{A}$ สามารถเขียนเป็น $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$

ในที่นี้ สัญลักษณ์ $\sum$ หมายถึงการบวก และ $i$ และ $j$ เป็นดัชนีที่วิ่งจาก $1$ ถึง $m$ และ $n$ ตามลำดับ ดังนั้น ผลรวมขององค์ประกอบทั้งหมดของเมทริกซ์ $\mathbf{A}$ คือการบวกองค์ประกอบทั้งหมดของเมทริกซ์เข้าด้วยกัน

แนวคิดนี้สามารถใช้กับเทนเซอร์ที่มีรูปร่างใดก็ได้ ตัวอย่างเช่น ผลรวมขององค์ประกอบทั้งหมดของเทนเซอร์ $3 \times 4 \times 5$ $\mathbf{B}$ สามารถเขียนเป็น $\sum_{i=1}^{3} \sum_{j=1}^{4} \sum_{k=1}^{5} b_{ijk}$

การคำนวณผลรวมขององค์ประกอบของเทนเซอร์เป็นการดำเนินการพื้นฐานในการประมวลผลข้อมูล สามารถใช้ในงานต่างๆ เช่น การคำนวณค่าเฉลี่ย การคำนวณความแปรปรวน และการคำนวณความสัมพันธ์ระหว่างตัวแปรต่างๆ

In [ ]:
A.shape, A.sum()

(torch.Size([5, 3, 2]), tensor(435))



ตามค่าเริ่มต้น การเรียกใช้ฟังก์ชัน `sum` จะ*ลด*เทนเซอร์ตามแกนทั้งหมดของเทนเซอร์ จนกระทั่งได้สเกลาร์ ไลบรารีของเรายังอนุญาตให้เรา[**ระบุแกนที่จะลดเทนเซอร์**] เพื่อบวกองค์ประกอบทั้งหมดตามแถว (แกน 0) เราระบุ `axis=0` ใน `sum` เนื่องจากเมทริกซ์อินพุตจะลดลงตามแกน 0 เพื่อสร้างเวกเตอร์เอาต์พุต จึงไม่มีแกนนี้ในรูปร่างของเอาต์พุต

ประโยคนี้หมายความว่าฟังก์ชัน `sum()` จะลดเทนเซอร์ตามแกนทั้งหมดของเทนเซอร์โดยค่าเริ่มต้น ซึ่งจะส่งผลให้ได้สเกลาร์ อย่างไรก็ตาม เราสามารถระบุแกนที่ต้องการลดเทนเซอร์ได้โดยใช้พารามิเตอร์ `axis` ตัวอย่างเช่น หากเราต้องการบวกองค์ประกอบทั้งหมดตามแถวของเมทริกซ์ เราสามารถใช้ฟังก์ชัน `sum()` ได้ดังนี้:

```python
import torch

A = torch.tensor([[1, 2, 3], [4, 5, 6]])

# บวกองค์ประกอบทั้งหมดตามแถวของเมทริกซ์
sum_of_rows = A.sum(dim=0)

# พิมพ์ผลลัพธ์
print(sum_of_rows)
```

ผลลัพธ์:

```
tensor([5., 7., 9.])
```

ดังที่คุณเห็น แกน 0 จะหายไปจากรูปร่างของเอาต์พุต เนื่องจากเมทริกซ์อินพุตจะลดลงตามแกน 0 เพื่อสร้างเวกเตอร์เอาต์พุต

การระบุแกนที่ต้องการลดเทนเซอร์เป็นคุณสมบัติที่มีประโยชน์ของฟังก์ชัน `sum()` ซึ่งช่วยให้เราสามารถคำนวณผลรวมขององค์ประกอบของเทนเซอร์ที่มีรูปร่างและขนาดใดก็ได้

In [ ]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(A)
# บวกองค์ประกอบทั้งหมดตามแถวของเมทริกซ์
sum_of_rows = A.sum(dim=0)

# พิมพ์ผลลัพธ์
print(sum_of_rows)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([5, 7, 9])
