<a href="https://colab.research.google.com/github/surapitttha/Deep-Learning-/blob/main/deep_learning_2_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีทักษะการเอาชีวิตรอดบางประการ ได้แก่:

(i) เทคนิคสำหรับการจัดเก็บและจัดการข้อมูล
(ii) ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
(iii) ความรู้เกี่ยวกับการดำเนินการพีชคณิตเชิงเส้นพื้นฐานที่เราใช้กับองค์ประกอบข้อมูลมิติสูง
(iv) แคลคูลัสเพียงพอที่จะกำหนดทิศทางในการปรับพารามิเตอร์แต่ละตัวเพื่อลดฟังก์ชันการสูญเสีย
(v) ความสามารถในการคำนวณอนุพันธ์โดยอัตโนมัติเพื่อให้คุณลืมแคลคูลัสที่คุณเพิ่งเรียนรู้ไปได้มาก
(vi) ความเข้าใจพื้นฐานเกี่ยวกับความน่าจะเป็น ซึ่งเป็นภาษาหลักของเราสำหรับการใช้เหตุผลภายใต้ความไม่แน่นอน
(vii) ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการเมื่อคุณติดขัด

โดยสรุป บทนี้จะให้คำแนะนำเบื้องต้นอย่างรวดเร็วเกี่ยวกับพื้นฐานที่คุณจำเป็นต้องรู้เพื่อติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้

**สรุป**

ในการเตรียมพร้อมสำหรับการเรียนรู้เชิงลึก คุณจะต้องมีพื้นฐานในด้านต่อไปนี้:

* เทคนิคการจัดเก็บและจัดการข้อมูล
* ไลบรารีสำหรับการนำเข้าและประมวลผลข้อมูลจากแหล่งต่างๆ
* พีชคณิตเชิงเส้นพื้นฐาน
* แคลคูลัสพื้นฐาน
* การคำนวณอนุพันธ์โดยอัตโนมัติ
* ความน่าจะเป็น
* ความสามารถในการค้นหาคำตอบในเอกสารอย่างเป็นทางการ

บทนี้จะให้คำแนะนำเบื้องต้นเกี่ยวกับพื้นฐานเหล่านี้ เพื่อให้คุณสามารถติดตามเนื้อหาทางเทคนิคส่วนใหญ่ในหนังสือเล่มนี้ได้

#2.1 Data Manipulation


2.1.1 Getting Started

To start, we import the PyTorch library. Note that the package name is torch.


In [1]:
import torch

**การแปลและเรียบเรียง**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ในกรณีหนึ่งมิติ นั่นคือ เมื่อมีเพียงแกนเดียว เราจะเรียก tensor ว่าเวกเตอร์ ด้วยแกนสองแกน Tensor จะเรียกว่าเมทริกซ์ ด้วยแกนมากกว่า 2 แกน เราจะลบชื่อเฉพาะออกและเรียกวัตถุนี้ว่าเทนเซอร์อันดับ k

PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า ตัวอย่างเช่น ด้วยการเรียกใช้ arange(n) เราสามารถสร้างเวกเตอร์ของค่าที่มีระยะห่างเท่ากัน โดยเริ่มต้นที่ 0 (รวม) และสิ้นสุดที่ n (ไม่รวม) โดยค่าเริ่มต้น ขนาดของช่วงคือ 1 เว้นแต่จะระบุไว้เป็นอย่างอื่น เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**สรุป**

Tensor เป็นอาร์เรย์ของค่าตัวเลขที่มีมิติได้หลายมิติ ใน PyTorch มีฟังก์ชันมากมายสำหรับสร้างเทนเซอร์ใหม่ที่เติมค่าไว้ล่วงหน้า เทนเซอร์ใหม่จะถูกจัดเก็บในหน่วยความจำหลักและกำหนดสำหรับการคำนวณบน CPU

**คำศัพท์:**

* Tensor: เทนเซอร์
* Array: อาร์เรย์
* Dimension: มิติ
* Vector: เวกเตอร์
* Matrix: เมทริกซ์
* Order: อันดับ
* Main memory: หน่วยความจำหลัก
* CPU-based computation: การคำนวณบน CPU

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

ค่าแต่ละค่าในเทนเซอร์เรียกว่าองค์ประกอบของเทนเซอร์ เทนเซอร์ x มี 12 องค์ประกอบ

เราสามารถตรวจสอบจำนวนองค์ประกอบทั้งหมดในเทนเซอร์ผ่านเมธอด numel ของเทนเซอร์ดังกล่าว

In [3]:
x.numel()

12

เราสามารถเข้าถึงรูปร่างของเทนเซอร์ (ความยาวตามแต่ละแกน) โดยการตรวจสอบแอตทริบิวต์ shape ของเทนเซอร์นั้น เนื่องจากเรากำลังจัดการกับเวกเตอร์ที่นี่ รูปร่างจึงมีเพียงองค์ประกอบเดียวและเหมือนกับขนาด

In [4]:
x.shape

torch.Size([12])


การแปลภาษา

เราสามารถเปลี่ยนรูปร่างของเทนเซอร์ได้โดยไม่เปลี่ยนแปลงขนาดหรือค่าของเทนเซอร์นั้น โดยการเรียกใช้ reshape ตัวอย่างเช่น เราสามารถแปลงเวกเตอร์ x ที่มีรูปร่าง (12,) เป็นเมทริกซ์ X ที่มีรูปร่าง (3, 4) ได้ เทนเซอร์ใหม่นี้จะเก็บองค์ประกอบทั้งหมดไว้ แต่จัดเรียงใหม่เป็นเมทริกซ์ โปรดสังเกตว่าองค์ประกอบของเวกเตอร์ของเราจะถูกวางเรียงทีละแถว ดังนั้น x[3] == X[0, 3]

In [5]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

โปรดสังเกตว่าการระบุทุกองค์ประกอบของรูปร่างเพื่อ reshape เป็นสิ่งที่ไม่จำเป็น เนื่องจากเรารู้ขนาดของเทนเซอร์ของเราอยู่แล้ว เราสามารถคำนวณองค์ประกอบหนึ่งของรูปร่างได้โดยกำหนดส่วนที่เหลือ ตัวอย่างเช่น กำหนดเทนเซอร์ที่มีขนาด n และรูปร่างเป้าหมาย (h, w) เรารู้ว่า w = n/h เพื่ออนุมานองค์ประกอบหนึ่งของรูปร่างโดยอัตโนมัติ เราสามารถใส่ -1 สำหรับองค์ประกอบของรูปร่างที่ควรอนุมานโดยอัตโนมัติ ในกรณีของเรา แทนที่จะเรียก x.reshape(3, 4) เราอาจเรียก x.reshape(-1, 4) หรือ x.reshape(3, -1) ได้เทียบเท่ากัน

ผู้ปฏิบัติงานมักต้องทำงานกับเทนเซอร์ที่เริ่มต้นเพื่อให้มีค่า 0 หรือ 1 ทั้งหมด เราสามารถสร้างเทนเซอร์ที่มีองค์ประกอบทั้งหมดตั้งเป็น 0 และรูปร่างของ (2, 3, 4) ได้ผ่านฟังก์ชัน zeros

In [8]:
x.reshape(4,-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [9]:
x.reshape(2,-1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [6]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.zeros(2,3,4).shape

torch.Size([2, 3, 4])

ในทำนองเดียวกัน เราสามารถสร้างเทนเซอร์ที่มีค่า 1 ทั้งหมดได้โดยการเรียกใช้ ones

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

เรามักต้องการสุ่มตัวอย่างแต่ละองค์ประกอบแบบสุ่ม (และไม่ขึ้นต่อกัน) จากฟังก์ชันการแจกแจงความน่าจะเป็นที่กำหนด ตัวอย่างเช่น พารามิเตอร์ของเครือข่ายประสาทมักเริ่มต้นแบบสุ่ม สนิปเป็ตต่อไปนี้สร้างเทนเซอร์ที่มีองค์ประกอบที่วาดจากฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ) โดยมีค่าเฉลี่ย 0 และส่วนเบี่ยงเบนมาตรฐาน 1

In [11]:
import torch

# Create a tensor of elements drawn from a standard Gaussian distribution
X = torch.randn((2, 3, 4))

# Print the tensor
print(X)


tensor([[[ 7.9948e-01, -5.8139e-01, -2.6846e-01,  6.2386e-01],
         [-5.6546e-01,  1.7168e+00,  6.3314e-01,  1.1047e+00],
         [ 1.1252e-03, -1.2404e+00,  1.0591e+00,  2.8100e-01]],

        [[ 7.8367e-01,  2.8471e-01, -1.9310e+00,  3.3191e-01],
         [-1.7737e-01,  1.2246e+00, -1.7026e-01, -5.4285e-01],
         [ 1.5949e+00,  4.5789e-01,  5.9535e-01,  1.5532e-02]]])


**คำศัพท์:**

* Random sample: การสุ่มตัวอย่าง
* Independently: ไม่ขึ้นต่อกัน
* Probability distribution: ฟังก์ชันการแจกแจงความน่าจะเป็น
* Neural network parameters: พารามิเตอร์ของเครือข่ายประสาท
* Standard Gaussian distribution: ฟังก์ชันการแจกแจงแบบเกาส์มาตรฐาน (ปกติ)
* Mean: ค่าเฉลี่ย
* Standard deviation: ส่วนเบี่ยงเบนมาตรฐาน


ช่ครับ ในที่สุด เราก็สามารถสร้างเทนเซอร์ได้โดยการให้ค่าที่แน่นอนสำหรับแต่ละองค์ประกอบโดยการให้รายการ (อาจซ้อนกันได้) ของ Python list(s) ที่มีค่าตัวเลข ในที่นี้ เราสร้างเมทริกซ์ที่มีรายการของรายการ โดยที่รายการนอกสุดสอดคล้องกับแกน 0 และรายการด้านในสอดคล้องกับแกน 1

In [13]:
import torch

# Create a matrix with a list of lists
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

# Print the tensor
print(X)
print(Y)


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [14]:
X.shape

torch.Size([2, 3])

In [15]:
Y.shape

torch.Size([3, 4])

2.1.2 Indexing and Slicing

ถูกแล้วครับ ดังเช่น Python lists เราสามารถเข้าถึงองค์ประกอบของเทนเซอร์ได้โดยการทำดัชนี (เริ่มต้นที่ 0) เพื่อเข้าถึงองค์ประกอบโดยอิงตามตำแหน่งขององค์ประกอบนั้นเมื่อเทียบกับส่วนท้ายของรายการ เราสามารถใช้การทำดัชนีแบบลบได้ ในที่สุด เราสามารถเข้าถึงช่วงทั้งหมดของดัชนีผ่านการตัดแบ่ง (เช่น X[start:stop]) โดยค่าที่ส่งกลับจะรวมดัชนีแรก (start) แต่ไม่รวมดัชนีสุดท้าย (stop) ในที่สุด เมื่อระบุดัชนีหรือการตัดแบ่งเพียงอันเดียวสำหรับเทนเซอร์อันดับ k จะถูกนำไปใช้ตามแกน 0 ดังนั้น ในโค้ดต่อไปนี้ [-1] จะเลือกแถวสุดท้าย และ [1:3] จะเลือกแถวที่สองและสาม

In [27]:
X = torch.arange(12, dtype=torch.float32)
X = X.reshape(3,4)

In [28]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access the last row using negative indexing
last_row = X[-1]

# Print the last row
print(last_row)

# Access the second and third rows using slicing
second_and_third_rows = X[1:3]

# Print the second and third rows
print(second_and_third_rows)

tensor([4, 5, 6])
tensor([[4, 5, 6]])


In [19]:
X[1][2]

tensor(6)

In [29]:
X[1,2]

tensor(6.)

ใช่ครับ นอกเหนือจากการอ่านองค์ประกอบของเมทริกซ์แล้ว เรายังสามารถเขียนองค์ประกอบของเมทริกซ์ได้โดยการระบุดัชนี

In [30]:
X[1, 2] = 17

In [31]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
#หรือ
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set the element at (1, 2) to 10
X[1, 2] = 10

# Print the matrix
print(X)

tensor([[ 1,  2,  3],
        [ 4,  5, 10]])


เราสามารถใช้การทำดัชนีและการตัดแบ่งเพื่อกำหนดช่วงขององค์ประกอบให้กับค่าใหม่ได้ ตัวอย่างเช่น โค้ดต่อไปนี้จะตั้งค่าองค์ประกอบทั้งหมดในแถวที่สองให้เป็น 7:

In [33]:
import torch

# Create a matrix
X = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Set all the elements in the second row to 7
X[1, :] = 7

# Print the matrix
print(X)


tensor([[1, 2, 3],
        [7, 7, 7]])


In [39]:
R = torch.arange(50,dtype=torch.float).reshape(5,10)
R

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [41]:
R[0,:] = 111
R[2,:] = 33
R

tensor([[111., 111., 111., 111., 111., 111., 111., 111., 111., 111.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
        [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.],
        [ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
        [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.]])

2.1.3 Operations

ใช่ครับ ตอนนี้ที่เรารู้วิธีสร้างเทนเซอร์และวิธีอ่านและเขียนองค์ประกอบของเทนเซอร์แล้ว เราสามารถเริ่มจัดการเทนเซอร์ด้วยการดำเนินการทางคณิตศาสตร์ต่างๆ ได้แล้ว การดำเนินการที่เป็นประโยชน์ที่สุดประการหนึ่งคือการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ (elementwise operations) การดำเนินการเหล่านี้ใช้การดำเนินการสเกลาร์มาตรฐานกับแต่ละองค์ประกอบของเทนเซอร์ สำหรับฟังก์ชันที่ใช้เทนเซอร์สองตัวเป็นอินพุต การดำเนินการแบบองค์ประกอบต่อองค์ประกอบจะใช้ตัวดำเนินการไบนารีมาตรฐานกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกัน

เราสามารถสร้างฟังก์ชันแบบองค์ประกอบต่อองค์ประกอบจากฟังก์ชันใดก็ได้ที่แมปจากสเกลาร์เป็นสเกลาร์

ในสัญกรณ์ทางคณิตศาสตร์ เราใช้เครื่องหมาย 𝑓 : R → R เพื่อแสดงตัวดำเนินการสเกลาร์แบบยูนารี (รับอินพุตหนึ่งตัว) ซึ่งหมายความว่าฟังก์ชันนี้แมปจากจำนวนจริงใด ๆ ไปยังจำนวนจริงอื่น ๆ ตัวดำเนินการส่วนใหญ่ รวมถึงตัวดำเนินการแบบยูนารีเช่น 𝑒
𝑥
สามารถใช้แบบองค์ประกอบต่อองค์ประกอบได้

ตัวอย่างการดำเนินการแบบองค์ประกอบต่อองค์ประกอบ ได้แก่:

* การบวก (+): C[i, j] = A[i, j] + B[i, j]
* การลบ (-): C[i, j] = A[i, j] - B[i, j]
* การคูณ (*): C[i, j] = A[i, j] * B[i, j]
* การหาร (/): C[i, j] = A[i, j] / B[i, j]
* การยกกำลัง (^): C[i, j] = A[i, j] ^ B[i, j]
* ฟังก์ชันตรีโกณมิติ: C[i, j] = sin(A[i, j])
* ฟังก์ชันการกระจายปกติแบบสะสม: C[i, j] = torch.distributions.Normal(0, 1).cdf(A[i, j])

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเทคนิคที่ทรงพลังในการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อประยุกต์การดำเนินการทางคณิตศาสตร์กับข้อมูลของเราได้อย่างมีประสิทธิภาพ

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [42]:
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
Z = X + Y

# Print the result
print(Z)


tensor([5, 7, 9])


In [43]:
X = torch.arange(10,dtype = torch.float).reshape(2,5)
torch.exp(X)


tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]])

ใช่ครับ ในทำนองเดียวกัน เราแสดงตัวดำเนินการสเกลาร์แบบไบนารี ซึ่งแมปคู่ของจำนวนจริงไปเป็นจำนวนจริง (ตัวเดียว) ผ่านเครื่องหมาย 𝑓 : R, R → R ในกรณีที่เวกเตอร์ u และ v สองตัวมีรูปร่างเดียวกัน และตัวดำเนินการแบบไบนารี 𝑓 เราสามารถสร้างเวกเตอร์ c = 𝐹(u, v) ได้โดยการตั้งค่า 𝑐𝑖 ← 𝑓 (𝑢𝑖
, 𝑣𝑖) สำหรับทุก 𝑖 โดยที่ 𝑐𝑖
, 𝑢𝑖
และ 𝑣𝑖 เป็นองค์ประกอบที่ 𝑖 ของเวกเตอร์ c, u และ v

ที่นี่ เราสร้างเวกเตอร์ที่ได้ค่าของ 𝐹 : R
𝑑
, R
𝑑 → R
𝑑 โดยการยกฟังก์ชันสเกลาร์ให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเวกเตอร์ ตัวดำเนินการเลขคณิตมาตรฐานทั่วไปสำหรับการบวก (+), การลบ (-), การคูณ (*), การหาร (/) และการยกกำลัง (**) มีการยกให้เป็นการดำเนินการแบบองค์ประกอบต่อองค์ประกอบของเทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง

**ตัวอย่าง**

```python
import torch

# Create two vectors
u = torch.tensor([1, 2, 3])
v = torch.tensor([4, 5, 6])

# Apply the elementwise addition operation
c = u + v

# Print the result
print(c)
```

Output:

```
tensor([5, 7, 9])
```

ในตัวอย่างนี้ เราใช้ตัวดำเนินการบวกแบบองค์ประกอบต่อองค์ประกอบกับสองเวกเตอร์เพื่อสร้างเวกเตอร์ใหม่ที่มีองค์ประกอบที่สอดคล้องกันของเวกเตอร์ u และ v เพิ่มเข้าด้วยกัน

เราสามารถใช้การดำเนินการแบบองค์ประกอบต่อองค์ประกอบกับฟังก์ชันที่ซับซ้อนกว่าได้เช่นกัน ตัวอย่างเช่น โค้ดต่อไปนี้จะใช้ฟังก์ชันดอทผลิตกับแต่ละคู่ขององค์ประกอบที่สอดคล้องกันของสองเทนเซอร์ X และ Y:

```python
import torch

# Create two tensors
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

# Apply the dot product function elementwise
c = torch.dot(X, Y)

# Print the result
print(c)
```

Output:

```
tensor(32)
```

การดำเนินการแบบองค์ประกอบต่อองค์ประกอบเป็นเครื่องมือที่ทรงพลังสำหรับการจัดการข้อมูลใน PyTorch เราสามารถใช้พวกมันเพื่อดำเนินการทางคณิตศาสตร์ที่หลากหลายกับเทนเซอร์ของเรา

**คำศัพท์:**

* Binary scalar operator: ตัวดำเนินการสเกลาร์แบบไบนารี
* Identically-shaped tensors: เทนเซอร์ที่มีรูปร่างเหมือนกันทุกรูปร่าง
* Vector-valued: ได้ค่าเป็นเวกเตอร์
* Lift: ยก

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [44]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

ใช่ครับ นอกเหนือจากการคำนวณแบบองค์ประกอบต่อองค์ประกอบแล้ว เรายังสามารถดำเนินการพีชคณิตเชิงเส้น เช่น ผลคูณจุดและการคูณเมทริกซ์ เราจะอธิบายเพิ่มเติมในหัวข้อ 2.3

เรายังสามารถรวมเทนเซอร์หลาย ๆ ตัวเข้าด้วยกัน โดยวางซ้อนกันแบบต่อเนื่องเพื่อสร้างเทนเซอร์ขนาดใหญ่กว่า เพียงแค่เราต้องระบุรายการของเทนเซอร์และบอกระบบตามแกนใดที่จะเชื่อมต่อ ตัวอย่างด้านล่างแสดงสิ่งที่เกิดขึ้นเมื่อเรารวมเมทริกซ์สองตัวเข้าด้วยกันตามแถว (แกน 0) แทนที่จะเป็นคอลัมน์ (แกน 1) เราจะเห็นว่าความยาวแกน 0 ของเอาต์พุตแรก (6) เป็นผลรวมของความยาวแกน 0 ของเทนเซอร์อินพุตทั้งสอง (3 + 3); ในขณะที่ความยาวแกน 1 ของเอาต์พุตที่สอง (8) เป็นผลรวมของความยาวแกน 1 ของเทนเซอร์อินพุตทั้งสอง (4 + 4)

**ตัวอย่าง**

```python
import torch

# Create two matrices
X = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
Y = torch.tensor([[9, 10, 11, 12], [13, 14, 15, 16]])

# Concatenate the matrices along rows
Z = torch.cat((X, Y), dim=0)

# Print the result
print(Z)
```

Output:

```
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]])
```

**คำศัพท์:**

* Concatenate: รวมเข้าด้วยกัน
* Stack: วางซ้อน
* Axis: แกน

หวังว่าคำตอบนี้จะเป็นประโยชน์นะครับ

In [45]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))